### ISSUE TITLE
Streamfield migration error

### ISSUE THREAD

**Issue by balazs-endresz** [torchbox/wagtail#1067]
Migrations for streamfields import the actual classes for custom blocks but this causes an error once they've been removed, and prevent creating new migrations. If possible they should reference all classes by a string instead of trying to import them.

**Comment by gasman** [comment]
See https://github.com/torchbox/wagtail/issues/823#issuecomment-74682820 for the detailed explanation of this.

In the general case, when you create a custom block type, you are committed to keeping those class definitions around forever (or else you have to rewrite your migrations). This is because the migration mechanism needs to be able to construct a fully working replica of the StreamField object as it existed at the time of the migration - string references are not enough.

For StreamBlock and StructBlock subclasses, I've been able to make an exception: there's a standardised way of subclassing these, which the base classes know about, and so the migration can contain a definition of the block that's expressed entirely in terms of the base StreamBlock / StructBlock class. For FieldBlock and everything else, this isn't possible, because we have no way of knowing what customisations have been made.

This will be part of the documentation, I promise :-)

**Comment by kaedroho** [comment]
I believe the reason for importing them is so the classes are guarenteed to exist in the project whenever old migrations get run, this lets any old data migrations to deserialise the streamfield with the blocktypes that were available at the time the migration was first created.

So if you change them, this is basically Djangos way of warning you to update your old migrations...

Theres another related issue that if you change a custom block, those changes are not recorded in a migration, so somebody relying on Django/Wagtail to be able to deserialise some streamfield data reliably may have issues if they just change one of their custom blocks.

Since all custom stream blocks are built up from the standard ones, would it be possible to serialise them in migrations that way? This has the advantage that changes to custom blocks get recorded as well. This may lead to large, horrible to read, migrations though

**Comment by balazs-endresz** [comment]
So as long as I'm subclassing only StreamBlock and StructBlock this shouldn't be an issue? Btw, I should have been using a ChooserBlock anyway, instead of a custom FieldBlock.

**Comment by gasman** [comment]
@kaedroho "Since all custom stream blocks are built up from the standard ones, would it be possible to serialise them in migrations that way?" - Yes, this is exactly what happens for subclasses of StreamBlock and StructBlock.

@balazs-endresz Yes, that's correct. (And, actually, ChooserBlock is another special case that can be safely subclassed: you can pass `choices` to the constructor, or create a subclass with a `choices` property.)
