### ISSUE TITLE
StreamField EmbedBlock renders the url only

### ISSUE THREAD

**Issue by balazs-endresz** [torchbox/wagtail#1098]
Given the following setup:
```
class EmbedOnImage(StructBlock):
    embed = EmbedBlock()
    background_image = ImageChooserBlock(required=False)

    class Meta:
        template = 'streamfield_blocks/embed_on_image.html'
```

`{{ self.embed }}` outputs the embed url only in `streamfield_blocks/embed_on_image.html`.

And `EmbedBlock.render_basic` is never called: https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailembeds/blocks.py#L8

Also, if I apply the embed filter too: `{{ self.embed|embed }}` then it outputs nothing because the embed filter won't call `embed_to_frontend_html` either, which would use the correct template to render it: https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailembeds/templatetags/wagtailembeds_tags.py#L14

**Comment by gasman** [comment]
This is the intended behaviour. When you access a child of a StructBlock, such as `self.embed`, you get back the raw value of the field - the URL string, in this case - rather than the block object that's aware of the correct rendering. This is needed so that you can do things like `{% if self.first_name == 'Bob' %}` in templates - if self.first_name returned a renderable block object rather than a string, it would never match.

However, I can see that this behaviour is confusing for blocks that have a string value, but have a non-standard rendering: namely, RichTextBlock, RawHTMLBlock and EmbedBlock. I'll have a think about whether there's a better way of doing this.

(Currently, one way to get at the proper rendering would be `{{ self.bound_blocks.embed.render }}`. Not sure why `{{ self.embed|embed }}` wouldn't work...)

**Comment by balazs-endresz** [comment]
`{{ self.bound_blocks.embed.render }}` does work indeed, thanks. Now I can see how this makes sense, but it was a bit unexpected for the first time.

And the `|embed` filter is not documented or used anywhere in wagtail actually. It seems to be a lower level alternative to `embed_to_frontend_html` that doesn't use the `embed_frontend.html` template. @kaedroho ?

**Comment by gasman** [comment]
> When you access a child of a StructBlock, such as self.embed, you get back the raw value of the field - the URL string, in this case - rather than the block object that's aware of the correct rendering.

On further consideration - EmbedBlock differs from RichTextBlock and RawHTMLBlock in that there's actually no reason to expect the native value of an EmbedBlock (i.e. the value you get when you access it as an item of a StructBlock) to be a string or string-like value. In particular, re the use case given above:

> This is needed so that you can do things like `{% if self.first_name == 'Bob' %}` in templates

there's no expectation for something like `{% if self.embed == 'https://www.youtube.com/watch?v=LxPXLIALJJI' %}` to work. Instead, it would be sensible for the value of `self.embed` to be a Python object which has a `url` property, and outputs the embed HTML when rendered in a template. The existing `wagtailembeds.Embed` model could be made to serve this purpose, although those are specific to a particular max_width parameter which would lead to a wasted lookup if the template actually wants to use a non-default max_width - so it's probably better to introduce a new class for this purpose.

The serialized value of an EmbedBlock can still be a plain URL string - `get_prep_value` and `to_python` will handle the type conversion. This would also be a good time to change the blocks API slightly so that the `default` parameter of a block definition gets passed through to_python - in this case, this means we can still say things like `EmbedBlock(default='https://www.youtube.com/watch?v=LxPXLIALJJI')` instead of having to pass a custom Python object. (Default values aren't too useful for EmbedBlock, but this solves a more general problem of blocks having non-simple native values - see https://github.com/torchbox/wagtail/blob/2940ea9c9beff94b47a46559937c8fb0512dd4d8/wagtail/wagtailcore/blocks/stream_block.py#L25-L27)

Will put together a PR along these lines.

**Comment by gasman** [comment]
Fix: https://github.com/torchbox/wagtail/pull/1357
