### ISSUE TITLE
Make Page.live default to False

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#1132]
See: https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/models.py#L272

I don't think it makes sense to create a page in published state, the signals won't fire and ``first_published_at`` will not be set. Pages should be created in unpublished state and then published using the ``publish()`` method of ``PageRevision``

**Comment by gasman** [comment]
The decision to set live=True by default was made to fit the philosophy that a Wagtail site should behave transparently as a data-driven Django app where possible, and Wagtail's own workflows should be made to fit that data model rather than the other way around - and I'd still stand by that.

To my mind, the fact that draft pages exist in the main data tables at all is more of a necessary evil than a feature... in an ideal world, the data that exists in the app-specific tables would exactly correspond to what's visible on the live site, and everything else would be held in Wagtail's own portion of the database (PageRevision and the like). On that basis, the natural thing to do when someone uses the basic Django/treebeard method calls in their application code to create a page object, would be to create it as a published page.

Can we not add logic to the `save()` method to ensure that the publish signals get fired when creating a page in the published state? I think that would be more correct than mandating a specific (and non-Django-ish) sequence of calls to create a published page.

**Comment by kaedroho** [comment]
That makes sense, will update my PR, thanks!
