### ISSUE TITLE
Pictures in StreamField cannot be put into order

### ISSUE THREAD

**Issue by taishizhiqiu** [torchbox/wagtail#1215]
The problem can be reproduced with the following model:
```python
class Homepage(Page):
    body = StreamField([
        (
            'portrait', blocks.StructBlock([
                ('title', blocks.CharBlock()),
                ('name', blocks.CharBlock()),
                ('portrait', blocks.ListBlock(blocks.StructBlock([
                    ('image', ImageChooserBlock()),
                    ('name', blocks.CharBlock()),
                    ('link', blocks.CharBlock(required=False)),
                    ('text', blocks.RichTextBlock()),
                    ])
                )
                )
            ])
        ),
    ])

Homepage.content_panels = [
    FieldPanel('title'),
    StreamFieldPanel('body'),
]
```
In wagtail admin, add a portrait structblock(`'portrait', blocks.StructBlock`), then add 11 listblocks(`'portrait', blocks.ListBlock()`) to it. Then the last listblock will appear in the third position and there is no way to put them in order.

Environment:
django 1.7.7
wagtail 1.0b1

**Comment by taishizhiqiu** [comment]
```python
class test:
    test
```

**Comment by gasman** [comment]
Ack... that'll be because we're ordering ListBlock items alphabetically so that '11' comes before '2'. We fixed this for StreamBlock, but apparently forgot to fix it here too...

https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/blocks/list_block.py#L102
https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/blocks/stream_block.py#L142

Thanks for the report!
