### ISSUE TITLE
Too long url_path causes crash

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#1216]
The slug isn't being validated properly at the form level. When users add a too long slug, everything crashes as this slug gets sent to the database without being checked first.

PR will follow shortly...

**Comment by gasman** [comment]
The problem is not with the validation on the slug field - the input field sets a max length of 255, and if a longer string is passed in (by hacking the input field HTML) the validation kicks in as expected.

The problem is that `url_path` also has a limit of 255 characters, so a slug that is close to this length is liable to push it over the limit. This is only really an issue since we increased the max slug length from 50 to 255 in bd28d9288ab1d718e2e3a3a78d5e9a263c244fa7 - it's possible to run into this on 0.8.x too, but only by going >5 levels deep with long slugs at each level. Given that the fix is going to involve a schema change, I propose that we fix this for 1.0 instead.
