### ISSUE TITLE
[Feature]Feed syndication for wagtail pages

### ISSUE THREAD

**Issue by SalahAdDin** [torchbox/wagtail#1341]
Maybe some people will need feeds for their pages, and now there aren't tutorials for to this, can anyone help us with this?

**Comment by zerolab** [comment]
Hi @SalahAdDin,

Implementing feeds in a Wagtail build is as simple as adding feeds to any Django project. Your best reference is https://docs.djangoproject.com/en/1.8/ref/contrib/syndication/

For a real life usage example have a look at https://github.com/torchbox/wagtail-torchbox/blob/master/torchbox/feeds.py and https://github.com/torchbox/wagtail-torchbox/blob/master/torchbox/urls.py

Wagtail's Page model is only aware of the custom model title and slug. Anything else is custom to a particular app or site. I can see the use for a contributed app that will "listen" to any additional fields to include in the feed, similar to how one can define what fields are indexed with wagtailsearch.

Not sure what the other think, but my money is on a contrib module rather than a core component.

**Comment by SalahAdDin** [comment]
Oh man, thank you very much!!!
You are a awesome guys.
