### ISSUE TITLE
update requirements

### ISSUE THREAD

**Issue by rcorzogutierrez** [torchbox/wagtail#1398]
installation finally I stay as follows

![cmd](https://cloud.githubusercontent.com/assets/5765375/8117024/f3e66696-104a-11e5-9871-282c96a286b6.PNG)

**Comment by gasman** [comment]
We don't include all of these in requirements.txt, because many of them are dependencies of other packages and get installed automatically. Keeping the version numbers up to date in requirements.txt would just create unnecessary work.

Is the current requirements.txt failing? If so, please can you give more details of the error?

**Comment by rcorzogutierrez** [comment]
no error with the dependencies, just info. thanks
