### ISSUE TITLE
Track changes implementation

### ISSUE THREAD

**Issue by pcraston** [torchbox/wagtail#1401]
We've recently had a feature request to add "track changes" functionality to the wagtail editing interface in our CMS project. For a different project, I've been working on adapting the ice.js package (by the NY Times CMS team) to work with tinyMCE 4 (https://github.com/NYTimes/ice/pull/116).

Although we're using ice.js with tinyMCE, ice.js can actually be attached to any contenteditable element. Haven't looked into the details but I guess we should be able to add ice.js to wagtail via a hook to halo.js.

However, I was wondering if this might be something that you would consider adding to the wagtail core? (If yes, we would look at doing a PR instead)

**Comment by davecranwell** [comment]
As you may have seen on the developers list recently (https://groups.google.com/d/msgid/wagtail-developers/DA018AA1-5C1E-43B3-95E3-2A1C6344F22D%40torchbox.com) we've been discussing the uncertain future of Hallo in Wagtail, or any WYSIWYG editor for that matter.

In short: we might ditch third party editors completely. The timeline is currently unclear and we might investigate replacement editors in the interim, so I'm not sure what to advise here. 

I think a PR might never get merged due to our plans for the future. I'd suggest instead that you perhaps make an app (or just a Gist) which you host publicly yourself. We'd be happy to list it here: https://github.com/torchbox/wagtail/wiki/Contributed-apps-and-website-code

**Comment by pcraston** [comment]
OK, thanks for the info!
