### ISSUE TITLE
Snippets can't inherit from AbstractForm

### ISSUE THREAD

**Issue by lee-kagiso** [torchbox/wagtail#1456]
I am trying to create a Poll using a snippet.
I see my form fields just get ignored in the Snippets menu item, as well as in my template?

```py
 class PollFormField(AbstractFormField):                         
     page = ParentalKey('Poll', related_name='form_fields')      
                                                                 
                                                                 
 @register_snippet                                               
 class Poll(AbstractForm):                                       
     intro = StreamField([                                       
         ('heading', blocks.CharBlock(classname='full title')),  
         ('html', blocks.RawHTMLBlock()),                        
         ('image', ImageChooserBlock()),                         
         ('paragraph', blocks.RichTextBlock()),                  
         ('video', EmbedBlock()),                                
     ])                                                          
                                                                 
     thank_you_text = StreamField([                              
         ('heading', blocks.CharBlock(classname='full title')),  
         ('html', blocks.RawHTMLBlock()),                        
         ('image', ImageChooserBlock()),                         
         ('paragraph', blocks.RichTextBlock()),                  
         ('video', EmbedBlock()),                                
     ])                                                          
                                                                 
     content_panels = [                                          
         FieldPanel('title', classname='full title'),            
         StreamFieldPanel('intro'),                              
         InlinePanel('form_fields', label='Questions'),          
         StreamFieldPanel('thank_you_text'),                     
     ]                                                           
                                                                 
     def __str__(self):                                          
         return self.title
```

**Comment by gasman** [comment]
Hi @lee-kagiso,
To give the direct answer: snippets should use a definition named `panels`, not `content_panels`.

However - in this case, you should not use snippets for this. `AbstractForm` is a subclass of `Page`, and it isn't valid for a model to exist as both a snippet and a page.

(Snippets are for pieces of content that don't exist as part of the pages tree; if you try to create a Page model through the Snippets area, Wagtail will fail to give it a location within the tree, and this will certainly throw errors later on. `AbstractForm` models need to exist in the pages tree - even if your site visitors never view them directly - because there needs to be a URL to post the form submission to.)

What I'd suggest here:

* Remove the `@register_snippet` line. Editors can still create polls through the 'Pages' area of Wagtail admin. (It's probably a good idea to create a new 'polls' section within the pages tree for this.)
* On your page types that support inserting a poll: rather than using `SnippetChooserPanel('poll', Poll)` or `SnippetChooserBlock(Poll)`, use `PageChooserPanel('poll', page_type=Poll)` or `PageChooserBlock()` instead.
* The templates for those pages can still access `self.poll.title`, `self.poll.form_fields` etc, in the same way as if you were using snippets.

**Comment by lee-kagiso** [comment]
Thanks, I actually started doing that as plan B.

I can't get my form fields to render though?

Here is my html snippet:
```html
 <section class='poll'>                                   
   <h1>{{ self.poll.title }}</h1>                         
   <div>                                                  
     {{ self.poll.intro|safe }}                           
     <form action="{% pageurl self.poll %}" method="POST">
       {% csrf_token %}                                   
       {{ self.poll.get_form.as_p }}  ->>>>>>> Issue here nothing displaying                    
       <button>Submit</button`>                           
     </form>                                              
   </div>                                                 
 </section>                                               
```

Using `{{ self.poll.form_fields.as_p }}` doesn't work either

**Comment by gasman** [comment]
Please could you ask this on the [Google group](https://groups.google.com/forum/#!forum/wagtail)? We'd prefer to keep Github issues for bug reports / feature requests only.
