### ISSUE TITLE
Remove default richtext image formats

### ISSUE THREAD

**Issue by michaelfillier** [torchbox/wagtail#1471]
Is there a way to remove the default image formats provided by wagtail. "Full width", "Left-aligned" and "Right-aligned".

We are using register_image_format for our custom sizes as it is a perfect way to add the right css classes and tie the images into our css framework. We are not using the default options and would like to exclude them from the admin interface, since they will produce undesired results.

**Comment by gasman** [comment]
Hi @michaelfillier,
You can do this with the `unregister_image_format` function:

    from wagtail.wagtailimages.formats import unregister_image_format
    unregister_image_format('fullwidth')
    unregister_image_format('left')
    unregister_image_format('right')

(Note that this will cause any existing pages using these image formats to throw an error when viewed or edited. It's on our todo list to change this behaviour so that unregistered image formats are just hidden from the admin interface, rather than being forgotten completely...)

**Comment by michaelfillier** [comment]
Thank you.

**Comment by rjsnh1522** [comment]
I am still facing the issue of error page when i unregister_image_format.
is it solved . or do you have any idea how can i remove image formats without getting error for each format
