### ISSUE TITLE
Improve page-level group permission UI/explanation

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#1488]
At present the page permissions assignable to a user group are added via a series of dropdowns and act _cumulatively_, rather than in a trumping fashion E.g "Publish any page" does not trump "Add/edit pages you own", but rather both these permissions need adding individually for each section in question, for all of add, edit and publish permissions to work.

This is particularly confusing because the "object permissions" above use checkboxes to imply the cumulative approach, so the existence of dropdowns for pages suggest a different mechanism.

Suggest we change the dropdowns to also use checkboxes. 

An interim solution might just be to add help text explaining the process.

**Comment by gasman** [comment]
Changing the interface to use checkboxes turns out to be deceptively complicated - I've tried to do this for the new collections permission interface, and have had to admit defeat...

The natural way to try and implement it is a formset, with one form per row of the table. This formset cannot be a straightforward InlineFormSet, because each form is managing multiple database objects (namely, one GroupPagePermission object for each checkbox) - it's an entirely new kind of formset.

So, this new formset type needs a way to keep track of which forms are which, as they get added and deleted. ModelFormSet and InlineFormSet do this by outputting a hidden field containing the ID of the model instance that backs the form. But in our case, there is no single database object that maps to the form - rather, the form is uniquely identified by a tuple of (group_id, page_id). Except we can't guarantee that the page_id will remain static for a given form - the user might change it, using the page chooser widget. That probably means we have to have a hidden field to store the original page ID, and different code paths in the form's save() method depending on whether the user has changed it or not. So what this amounts to is a new formset type, as complex as InlineFormSet if not more, which cannot be implemented as a logical extension of InlineFormSet. Fun times :-/
