### ISSUE TITLE
Enforce slug uniqueness at the model level

### ISSUE THREAD

**Issue by DiogoMarques29** [torchbox/wagtail#1518]
I saw in your code here on github that this feature is not yet developed. In which version will this be fixed?

**Comment by gasman** [comment]
Hi @DiogoMarques29,
We do enforce uniqueness at the view level, when editing pages in the Wagtail admin: https://github.com/torchbox/wagtail/blob/v1.0rc2/wagtail/wagtailadmin/views/pages.py#L319

Validating this at the model level would be neater (so that the check is applied when running scripts to import articles, for example), but the view-level check is sufficient for most purposes, so it isn't currently a high priority to change this.

**Comment by DiogoMarques29** [comment]
Hi again.
I am using a custom app we made (https://github.com/infoportugal/wagtail-modeltranslation), in that app we have a custom model that rebuilds the panels with fields for all languages hiding the original field, for example, by having slug field on translation options the form will only have slug_pt, slug_en and so on and not the original slug field, so those fields will not be validated when the form validation occurs. That is why we need the validation at the model level, or we will be forced to make our own overrides to the validation forms. I'm guessing that is what we are going to do!

Thanks for you help
