### ISSUE TITLE
Notification emails are sent "to:" all recipients in the clear.

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#1559]
Moderation notification emails are sent with every recipient's email visible in the "to:" line, which seems yucky. BCC-ing everyone makes more sense.

**Comment by gasman** [comment]
A better solution would be to send a distinct email to each recipient. This would allow personalisation (such as greetings, and possibly an 'unsubscribe from these notifications' link with an embedded login token), and more importantly, is going to be necessary if/when we implement per-user language settings.

**Comment by davecranwell** [comment]
Ah yes, that would be preferable. 

I suppose there are some considerations about how mail servers might respond to Wagtail performing bulk emails, but they'd be just as concerned with a massive bcc, so perhaps it's no more problematic. Mailing would need to be queued, if it isn't already.

**Comment by gasman** [comment]
We previously had code to queue email using Celery when available, to account for this, but took it out because it was effectively pushing more setup demands on the developer without warning them: http://docs.wagtail.io/en/v1.0/releases/1.0.html#celery-no-longer-automatically-used-for-sending-notification-emails .

I think it makes sense for it to be the developer/administrator's responsibility for putting a suitably robust email infrastructure in place - something that Django already provides extensive configuration options for - rather than Wagtail trying to push one particular approach. Perhaps it would be a good idea to add a note about django-celery-email to the [performance section](http://docs.wagtail.io/en/v1.0/advanced_topics/performance.html) of the docs, when we make this change.

**Comment by davecranwell** [comment]
So without celery, would that mean the mailing process would be blocking?

**Comment by gasman** [comment]
I think so, yes - although that's where my knowledge of mail servers gets a bit hazy. It may well be that in the typical setup (SMTP to localhost), it's only blocking for as long as it takes to push the data to the local SMTP server, and the actual sending-across-the-internet bit happens asynchronously.

**Comment by mgd020** [comment]
Created #1973

**Comment by gasman** [comment]
Implemented in e18f877286308a8a172fcd99a4ea79d9f4aa3c14.
