### ISSUE TITLE
Customising the tabbed interface Documentation

### ISSUE THREAD

**Issue by jossingram** [torchbox/wagtail#1561]
http://docs.wagtail.io/en/v1.0/advanced_topics/customisation/page_editing_interface.html#customising-the-tabbed-interface

I couldn't get this bit to work until I added my model name like below, not sure if this is a mistake in the documentation or some difference in the way I've implemented things.

from wagtail.wagtailadmin.edit_handlers import TabbedInterface, ObjectList

class BlogPage(Page):
    # field definitions omitted

    BlogPage.content_panels = [
        FieldPanel('title', classname="full title"),
        FieldPanel('date'),
        FieldPanel('body', classname="full"),
    ]
     BlogPage.sidebar_content_panels = [
        SnippetChooserPanel('advert', Advert),
        InlinePanel('related_links', label="Related links"),
    ]

    BlogPage.edit_handler = TabbedInterface([
        ObjectList(BlogPage.content_panels, heading='Content'),
        ObjectList(BlogPage.sidebar_content_panels, heading='Sidebar content'),
        ObjectList(BlogPage.promote_panels, heading='Promote'),
        ObjectList(BlogPage.settings_panels, heading='Settings', classname="settings"),
    ])

**Comment by davecranwell** [comment]
The syntax in the docs is how I'd like model definitions to be written in future, but I don't believe it works like that quite yet. I think this may be a documentation mistake.

**Comment by gasman** [comment]
The version given in the documentation should work - previously the one barrier to writing panel definitions in that way was the need to reference the model name in `InlinePanel` declarations, but that's no longer required in 1.0.

@jossingram, can you check that you've indented your code in the same way as the example? The `content_panels`, `sidebar_content_panels` and `edit_handler` lines need to be indented within `class BlogPage(Page):`. (Conversely, in your version with the `BlogPage` model name included, those lines need to be at the same level as `class BlogPage(Page):`, otherwise `BlogPage` won't be defined at that point.)

**Comment by jossingram** [comment]
@gasman Sorry my bad, yes with the indents it works fine.
