### ISSUE TITLE
Non-swappable user model and data 

### ISSUE THREAD

**Issue by bennylope** [torchbox/wagtail#158]
I noticed that #58 did a little bit of work to make [swappable users](https://docs.djangoproject.com/en/1.6/topics/auth/customizing/#substituting-a-custom-user-model) work with Wagtail but there's still quite a lot of coupling to the `auth.User` model. 

I've started some work to amend this on [my fork](https://github.com/bennylope/wagtail/tree/fix-swappable-users), including updating the schema migrations (in the [main migrations](https://github.com/bennylope/wagtail/commit/3c39bb97bd990fb85a35929c16e04368d674559d) and [frozen ORM](https://github.com/bennylope/wagtail/commit/b3b1e2431b9ac381b02c2ef77ae8112bb609fd71)) but it requires additional work. I'd love to decouple this a bit since we regularly use custom user models, especially substituting an email address for username, and that would enable us and maybe others to use Wagtail.

Before I do any more, is there any interest in decoupling further, or is the team set on using `auth.User` and it's fields for Wagtail?

**Comment by gasman** [comment]
Hi @jsma,
I think the best approach is somewhere in between. Having to override the user management interface at the URL/view level certainly seems heavy-handed, and making the existing views flexible enough to accommodate custom User models would be much neater.

Given that Django 1.7 deprecates the pattern of a ModelForm that automatically picks up its field list from the model (and pushes you towards an explicit `fields` attribute instead), I think we ought to follow suit and require custom fields to be specified explicitly. Ideally we'd be able to do that by allowing the user to pass in a custom replacement for UserCreationForm / UserEditForm - but I see that wouldn't be enough as it stands, because the list of fields is also currently hard-coded in create.html / edit.html. Perhaps the answer is to shift some of that template structure back into the form objects - they could define overrideable `account_fields` and `roles_fields` properties, which can then be used to assemble the final `fields` property, as well as being looped over in the create.html / edit.html templates.

**Comment by gasman** [comment]
Fixed in #1388 (as far as allowing custom user models without a username field, at least - feel free to open new tickets if there are any residual issues around customisability of the user edit forms, or whatever...)
