### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by Tanyusha** [torchbox/wagtail#1586]
I need something like this:
![2015-08-07 12-14-35](https://cloud.githubusercontent.com/assets/5334201/9132703/d77107fa-3d0e-11e5-8826-5259bfb761dc.png)
How can I do this via wagtail?
Probably I can do this via snippets, but this way has some limitations: there is no buttons for adding, deletion and editing elements while creating and editing pages:
![2015-08-07 14-26-08 wagtail - new profile page - google chrome](https://cloud.githubusercontent.com/assets/5334201/9132887/5bc10676-3d10-11e5-9044-7ddaa61b8d99.png)
![2015-08-07 14-26-26 wagtail - new profile page - google chrome](https://cloud.githubusercontent.com/assets/5334201/9132891/62cde40c-3d10-11e5-8142-84ad18df2cbe.png)

**Comment by davecranwell** [comment]
This is currently not supported. Given our current UI workflow, the creation of a new snippet "on the fly" would be expected to be achieved inside a modal (like for uploading a new image/document). 

However since snippet models can contain any fields - themselves also invoking a modal - this can result in multiple nested modals, which our modal system currently doesn't support.

As this request is essentially the same as an existing one: #1144 I'll close this.
