### ISSUE TITLE
Review ababic/wagtailmodeladmin for consideration to adding to core

### ISSUE THREAD

**Issue by tomdyson** [torchbox/wagtail#1657]
See https://github.com/ababic/wagtailmodeladmin.

cc @ababic.

**Comment by ababic** [comment]
Really flattered to hear this guys. @gasman feel free to shout if you need anything (here/email/on the development board)

**Comment by tomdyson** [comment]
Hi @ababic, we'd like to get started with moving this into Wagtail itself. Could you please submit a PR adding this to wagtail.contrib? It will need tests and docs (mainly converting your README.md and moving it into /docs/reference/contrib/ ). Let us know if you need any help or advice. Thanks!

**Comment by ababic** [comment]
Okay, great. I'll try to get this actioned within the next couple of weeks.

I should probably say, I'm quite inexperienced at writing tests. So
whatever I do there will likely need a bit of refinement.

Also, the views include what are essentially class-based versions of the
snippet management views. So I'm not quite sure about how they logically
fit into a contrib module. My hope was that things would move in a more
class-based direction with more of the core stuff, giving me something to
extend, rather than replace. I guess that's something we'll need to review
a bit later.

Hi @ababic <https://github.com/ababic>, we'd like to get started with
moving this into Wagtail itself. Could you please submit a PR adding this
to wagtail.contrib? It will need tests and docs (mainly converting your
README.md and moving it into /docs/reference/contrib/ ). Let us know if you
need any help or advice. Thanks!

—
Reply to this email directly or view it on GitHub
<https://github.com/torchbox/wagtail/issues/1657#issuecomment-147413829>.

**Comment by tomdyson** [comment]
Hi @ababic we discussed this - ideally we'd move more core stuff into CBVs, as you say, giving you something to extend, but on balance we think it's more important to get these functional improvements out now and refactor at leisure. We're happy to review / refine tests.

**Comment by ababic** [comment]
Hi @tomdyson. I've converted the `css` in my app to `scss`, and renamed the `static` folder to `static_src` to match the approach used elsewhere, but can't seem to get the `static` folder to generate when running `gulp build`. Do I need to tell gulp about the added directory somehow, or does the contrib app need to be referenced somewhere?

**Comment by ababic** [comment]
Not to worry! Figured it out :)

**Comment by ababic** [comment]
Greetings all!

I've got it added and working okay locally, and have also add to the docs. The only outstanding thing is tests, but I don't see myself being very useful there at all. In order to get things moving, are you happy to accept the pull-request without the tests in place and have someone better-equipped look at that later?

**Comment by tomdyson** [comment]
Thanks, @ababic! Can you submit the PR so we can review and add / advise on tests?

**Comment by gasman** [comment]
Completed in #1829
