### ISSUE TITLE
Image filenames are not unique

### ISSUE THREAD

**Issue by danreeves** [torchbox/wagtail#1686]
If you upload more than one image with the same filename (and I assume extension) the image is overwritten and all previous images now point to the latest one uploaded.

Looking at the code and a quick search leads me to believe that this is because wagtailimages uses the `get_valid_name` but not the [`get_available_name ` method](https://docs.djangoproject.com/en/1.8/howto/custom-file-storage/#django.core.files.storage.get_available_name).

I'm using `storages.backends.s3boto.S3BotoStorage`.

Relevant requirements in my project:
```
Django>=1.8,<1.9
wagtail==1.1rc1
boto==2.38.0
django-storages-redux==1.3
```

Any quick fixes or advice on where I'm going wrong would be great.

**Comment by kaedroho** [comment]
It looks like this is the normal behaviour of ``S3BotoStorage``: https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto.py#L487-L492

This could be solved at the Wagtail end by checking the new filename against the other files in the images table.

Or maybe they would be willing to drop this check since Django have changed the way they handle filename clashes in 1.7.

**Comment by gasman** [comment]
If @kaedroho's assessment is correct, it looks like adding the setting `AWS_S3_FILE_OVERWRITE = False` should fix it.

Either way, closing this as it's a django-storages bug - S3BotoStorage's default implementation of `get_available_name` is clearly violating Django's spec (or taking an extremely dubious interpretation of the phrase 'available filename')...

**Comment by danreeves** [comment]
Thanks for the help; I'll take a look at `AWS_S3_FILE_OVERWRITE`.
