### ISSUE TITLE
PageRevision.content_json doesn't serialize StreamFields

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#1687]
http://docs.wagtail.io/en/v1.1/reference/pages/model_reference.html#wagtail.wagtailcore.models.PageRevision.content_json

If I run `page.get_latest_revision().content_json` I expect to see the data in a format like this:

```
[{
 "pk": 9,
 "model": "team.person",
 "fields": {
 "interview": [{
  "type": "discussion",
  "value": {
   "answer": "nmhbu?",
   "question": "What's up?"
   }
  }],
 "name": "Alex Gleason",
 "photo": null,
 "biography": "<p>Hello world.</p>",
 "job_title": "Developer",
 "personal_title": "Very Special",
 "work_title": "Hacker"
 }
}]
```

but instead it appears like this:

```
[{
 "pk": 9,
 "model": "team.person",
 "fields": {
 "interview": "[{\"type\": \"discussion\", \"value\": {\"answer\": \"nmhbu?\", \"question\": \"What's up?\"}}]",
 "name": "Alex Gleason",
 "photo": null,
 "biography": "<p>Hello world.</p>",
 "job_title": "Developer",
 "personal_title": "Very Special",
 "work_title": "Hacker"
 }
}]
```

**Comment by alexgleason** [comment]
On closer inspection, it [appears to be used to find the Page object for a PageRevision](https://github.com/torchbox/wagtail/blob/f47bb70ebafefd09d453b23036af5bf603f7124d/wagtail/wagtailcore/models.py#L1099).

Why is this exposed as part of the public API?

What I'm really looking for is `Page.get_content_as_json()`, which doesn't exist.

**Comment by gasman** [comment]
I wouldn't consider this a bug. `content_json` is the database-friendly representation of an article converted into JSON, and since StreamField data is already JSON within the database-friendly representation, it gets encoded twice.

It is primarily an internal feature, but it's in the documentation because it's something you might need to know about if you're updating article content programatically (e.g. in migrations).

**Comment by alexgleason** [comment]
Thank you for the clarification. :)
