### ISSUE TITLE
StreamField not working correctly in FireFox

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#1695]
Clicking to add a new block doesn't do anything in FireFox. It works as intended in Chrome.

I'm running the master branch of Wagtail, updated to the latest commit at the time of writing. I recall it working several days ago but I can't be sure since I use both browsers.

**Comment by davecranwell** [comment]
Hi @alexgleason I'm afraid I'm not experiencing this in FF 40.0.3, OSX, on Wagtail master.

One thought: have you run the gulp task to regenerate/watch the CSS from SASS? (http://docs.wagtail.io/en/v1.0/contributing/css_guidelines.html) It's a requirement of running from a Git checkout, rather than a package (which includes precompiled CSS).

If that doesn't solve your problems, please can you provide steps to replicate?

**Comment by alexgleason** [comment]
I'm not experiencing the problem anymore on the same laptop. I did run `npm run build` while trying to debug the issue as well as synced the repo with master and it still wasn't working. I don't know what it could have been. I was on a very slow connection at the time. But I just tried shutting off my internet entirely and couldn't reproduce it.

Anyway, thanks for looking into it! I was hoping it would be an "only me" thing.
