### ISSUE TITLE
add widget to StreamField

### ISSUE THREAD

**Issue by ciloeweb** [torchbox/wagtail#1833]
I need add widget ace editor to streamfield, I try this but it isn't working.

class HtmlBlock(blocks.FieldBlock):

    def __init__(self, required=True, help_text=None, max_length=None, min_length=None, **kwargs):
        self.field = forms.CharField(
            required=required, help_text=help_text, max_length=max_length, min_length=min_length,
            widget=AceWidget(mode='html', theme='twilight'))
        super(HtmlBlock, self).__init__(**kwargs)

    class Meta:
        icon = 'code'

**Comment by gasman** [comment]
It looks like this is a limitation of the django-ace component, unfortunately - it works by applying Javascript behaviour to the field on page load:

https://github.com/bradleyayers/django-ace/blob/master/django_ace/static/django_ace/widget.js#L144-L147

Since StreamField adds fields dynamically after the page has loaded, this won't work. The Ace editor could probably still be made to work, but it would require some custom coding to run the relevant JS each time a field is added.

**Comment by ciloeweb** [comment]
You can indicate where change, i try change the field.html but i don't know join the field.

Thanks.
