### ISSUE TITLE
Snippet chooser panel broken

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#1834]
Snippet chooser panel broken in latest master. commit from a couple of weeks ago works.
.
Sorry I can't give many details at the moment. I'll investigate this further and replace this description later

**Comment by gasman** [comment]
git bisect shows that the offending commit is d31e4cd032d38f6c816cf3c56115297c3c66d234

**Comment by gasman** [comment]
This is not specific to SnippetChooserPanel - it occurs on any initially-empty chooser for a non-nullable field. It seems that `get_related_model` returns the model that the foreign key is on, rather than the one the foreign key is pointing to, which means the related_model.DoesNotExist exception at https://github.com/torchbox/wagtail/commit/d31e4cd032d38f6c816cf3c56115297c3c66d234#diff-3eb06cf22d9b9742ad0aa1a58c9d76f5R533 is not caught.
