### ISSUE TITLE
Errors from embed chooser are not reported back to the user

### ISSUE THREAD

**Issue by dLook** [torchbox/wagtail#1885]
It seems that embed functionality of wagtail hello.js editor is not working. I tried to embed a link, modal comes up, everything is fine but when I press "Insert" I get nothing and browser displays this error:

(Firefox) TypeError: a is undefined rangy-core.js:33:479
(Chrome) rangy-core.js:33 Uncaught TypeError: Cannot read property 'nodeType' of undefined

But network data says everything is OK:
POST .../admin/embeds/chooser/upload/ 200 OK
After closing the modal window, embed link is not present.

**Comment by gasman** [comment]
Confirmed on latest master.

**Comment by gasman** [comment]
This was failing on my development copy because I had an invalid EMBEDLY_KEY in my settings. Embeds are working fine for me on a fresh install.

Which reveals that there is in fact a bug here: error messages are not being returned back to the user here. We'll need to fix this first before we know whether the embed is failing for an 'expected' reason (e.g. a misconfiguration like mine, a network error, or simply that your URL is not recognised as one of the embed providers on our list - https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailembeds/oembed_providers.py) or for an unexpected reason that requires further investigation.

**Comment by dLook** [comment]
I am sure it was because URL was not on the list of recognised embed providers because embeds from youtube and soundcloud works just fine. 
Didn't know that list exists.
