### ISSUE TITLE
ImageChooserPanel showing up as a <select> box

### ISSUE THREAD

**Issue by kunambi** [torchbox/wagtail#1912]
This issue has also been posted at https://bitbucket.org/takeflight/wagtailsettings/issues/3/, but seeing that it was some time since there was any activity in the project, I'm trying my luck here as well.

First of all, thank you for this useful app.

Following should create a default-looking image-upload-widget, but instead it shows up as a select-box with all images (that has been uploaded) listed:

```python
@register_setting(icon='cogs')
class BasicSettings(BaseSetting):
    logo = models.ForeignKey(
        'wagtailimages.Image', null=True, blank=True, on_delete=models.SET_NULL, related_name='+', verbose_name=_('Logotype')
    )

    content_panels = [
        ImageChooserPanel('logo'),
    ]
```

**Comment by gasman** [comment]
Your `content_panels` property should be `panels`. (It's called `content_panels` for pages because you're specifying the panels to appear under the 'content' tab - for settings and snippets, there are no tabs.)

This has caught a few people out - perhaps we should add a warning on startup whenever there are registered settings/snippets with a `content_panels` property but no `panels`...
