### ISSUE TITLE
Allow specifying multiple page types in PageChooserPanel

### ISSUE THREAD

**Issue by jmiguelv** [torchbox/wagtail#199]
Currently when adding links to pages it is possible to link to every page on the site. It would be great if the page links could be limited according to specified page types.

**Comment by gasman** [comment]
Autodetecting page type from the ForeignKey is being addressed in #509. Will keep this ticket open for the other request, allowing multiple types to be specified. (I'm not 100% sure if the superclass approach works - in particular I suspect it might fail on abstract base classes, because we're using ContentTypes, and I don't think abstract classes have those. Either way, we can still improve things by having it accept an arbitrary list of page types.)

**Comment by salvadormrf** [comment]
Would be nice to have this feature. 
I have different article types and from the section the admin can feature an article.

**Comment by ahayzen** [comment]
This affects me as well, I was trying to create a PageChooserPanel that filters by two page types. It would by useful if you could pass a list of page types to filter with.

**Comment by gasman** [comment]
Final version of this feature was merged in #1621.
