### ISSUE TITLE
Snippet and Image delete not working with CSRF Middleware disabled

### ISSUE THREAD

**Issue by michaelfillier** [torchbox/wagtail#2033]
We were having some issues with csrf on our server. So we had to disable the middleware as a temporary solution. Since doing this, deletion of images and snippets in the admin have stopped working. The page simply reloads without deleting the object.

I have re-enabled the middleware and was able to delete the objects.

**Comment by gasman** [comment]
I'll bet this is because the view that handles deletion is checking for the form submission using `if request.POST:` rather than `if request.method == 'POST':`. The former will only return true for a *non-empty* submission - and in normal circumstances the form only consists of the CSRF token and the 'delete' button (which is not given a name attribute, so is not included in the form submission). We should change these checks (here and elsewhere in the Wagtail codebase) to use the latter version.

(I think we also have some unit tests that pass dummy data to work around this bug - it would be good to remove those workarounds at the same time...)

We'd strongly advise against disabling the CSRF middleware, but I agree that the Wagtail admin still ought to work correctly without it.

**Comment by gasman** [comment]
Have confirmed that this has been fixed by #2424.
