### ISSUE TITLE
Toolbar buttons in rich text fields stop being highlighted properly since v1.2

### ISSUE THREAD

**Issue by tadeo** [torchbox/wagtail#2040]
When bold, italic, headings or paragraphs are selected in a rich text field, the related button is not highlighted since v1.2

**Comment by gasman** [comment]
`git bisect` shows that this was broken by 015e9da9b83844e7f1de657339f45015cf13ac1b.

**Comment by gasman** [comment]
According to #1746, the CSS change which caused this (by effectively overriding the button highlight style so that it only occurs on mouse hover) was a fix for this issue:

> When the cursor is positioned directly over where a button would appear in the Hallo toolbar, then the toolbar appears, the button is solid white until the cursor is moved. This has been fixed.

- which - according to my comment at https://github.com/torchbox/wagtail/pull/1746#issuecomment-151467730 - is a bug that I was never able to replicate in the first place (and still can't). As such, I have no qualms about reverting this :-)

Have submitted PR #2042 to revert this - any objections @alexgleason?

**Comment by alexgleason** [comment]
@gasman Go for it! That code definitely shouldn't have to exist... not sure why it was working for me but is causing a problem now.
