### ISSUE TITLE
Submit for moderation

### ISSUE THREAD

**Issue by ciloeweb** [torchbox/wagtail#2095]
Hi, guys!

I have a question, because it shows the option to submit for moderation to a user with moderator role or admin role, i think this option only show the editor rol.

![submit](https://cloud.githubusercontent.com/assets/6557784/12209909/d15ac294-b61b-11e5-9c3b-1168df7e8631.png)

**Comment by gasman** [comment]
Hi @ciloeweb,
This behaviour is intentional. Even if a user has the ability to publish a page themselves, there may still be occasions when they want it to be checked by another user - for example, the text may need to be checked by a lawyer (or simply checked for spelling / grammar errors). For this reason, the option is still useful, even if it's not strictly necessary.

**Comment by ciloeweb** [comment]
Thank you very much! , just want to be sure!!!

**Comment by SalahAdDin** [comment]
Hi @ciloeweb, how did you chagen the green color to orange color? It looks very good.
