### ISSUE TITLE
Trailing slash

### ISSUE THREAD

**Issue by davejacobs** [torchbox/wagtail#2096]
How do I stop wagtail from auto-appending a trailing slash when I navigate to wagtail-controlled pages? I've set `APPEND_SLASH` to `False`, removed Wagtail redirect middleware, and even tried adding `django-unslashed` (and `REMOVE_SLASH = True`) per its docs, but redirects keep happening. Any advice?

**Comment by kaedroho** [comment]
This isn't something we've looked into much yet. But I'd be happy to see Wagtail support ``APPEND_SLASH=False`` if it's not too tricky to do.

But it might be able to do it now by copying and modifying this URLconf entry (https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/urls.py#L8-L13) making the trailing slashes optional. Then implement your own version of the ``{% pageurl %}`` templatetag to remove the trailing slash.

**Comment by davejacobs** [comment]
Thanks for the pointers, I'll see what I can come up with.

**Comment by jangondol** [comment]
One option would be to have something like `WAGTAIL_APPEND_SLASH` or we could go for something more generic like `WAGTAIL_URL_APPEND` which could be set to "/" (slash) or "" (nothing, i.e. no trailing slash) or something like ".html" (give the appearance that the wagtail page is a static page -- could be useful). Any thoughts?

**Comment by davejacobs** [comment]
Either of those would work for my purposes. I don't need the `.html` functionality, but I could understand how that would be useful for some people. I've tried modifying `urlpatterns`, per @kaedroho's suggestion, and it works for me. However, I haven't been able to come up with a super-efficient regex to replace the original with, and I also have to manually link to `/admin/` (with a slash) to make redirection working.

Official support would be great, and either of the options you propose would work well for me. Thanks for asking!

**Comment by jangondol** [comment]
Yes, @davejacobs, agree that official support would be very nice. That `.html` functionality could be useful in a number of ways, e.g. for making migration from an older CMS  easier (keeping existing URLs is sometimes desirable). Some sites use `.php`, some have `.htm`, `.html`, etc.. Being able to append slash, no slash, or anything at all in an easy and documented way would be super helpful.

**Comment by gasman** [comment]
I'd be happy to see the no-slash format supported. The slash-appended version makes the logic slightly simpler, as we don't need a special case for the root path `/` (which, obviously, always ends in a slash...) but it's no big deal if we need to add a few more edge-case checks.

`.html` suffixes are really a different thing to path separators, and I think it would be counter-productive to try and implement them with the same logic. You'd end up with http://example.com/blog/hello_world.html being a child of http://example.com/blog.html, which is a bit odd (and unlikely to match the scheme used by an older CMS).

**Comment by jangondol** [comment]
Well, one solution would be to have not only a `URL_SUFFIX`, but also a `URL_PREFIX`, e.g. `index` or `default` (which would modify URLs of pages with children, e.g. / -> /index.html, /blog/ -> /blog/index.html, etc.). To make things easy, we could live *without* `URL_PREFIX` and manually add a few redirects if needed.

Or perhaps there is another clean way to handle this? Ideas? :-) (Yes, file name extension should be avoided but being able to migrate from existing sites with [minimal URL changes](https://www.w3.org/Provider/Style/URI.html) would be a useful feature.)

**Comment by gasman** [comment]
@jangondol Sure it's possible, but once we start talking about different behaviours for pages with/without children (wouldn't that just introduce another opportunity for old URLs to break, when a single page is turned into a multi-page subsection? :-) ), it's not just a simple generalisation of `APPEND_SLASH` any more. That's why I think it's out of scope for this ticket.

**Comment by jangondol** [comment]
@gasman I see your point. Yes, the prefix could make things trickier. A customizable suffix (i.e., not just "slash" vs. "no slash" but also things like `.html`) would be still super helpful in several scenarios though.

Or perhaps I could just turn off trailing slash (once this is possible) and make sure the slug says `hello_world.html` instead of `hello_world`?

It would be cool to be able to somehow decouple the URL (at least for selected pages), so we could have `/blog/index.html` as a parent and `/blog/hello_world.html` as a child (instead of `/blog/index.html/hello_world.html`). But that is way outside of scope of this ticket.

**Comment by gasman** [comment]
@jangondol I think you're really better off using redirects for that. The message of the 'Cool URIs don't change' essay isn't "never change your URLs" - it's "choose URLs that don't expose the workings of your webserver, so that they won't have to change". `.html` extensions and index.html files break this guideline - they're an artefact of storing your pages as files on a filesystem, because filesystem structures don't perfectly match up to URL structures. In particular, index.html is just a workaround for the fact that a file can't directly be the child of another file. The right thing to do is to fix these 'bugs' in your URL scheme, not try to bend Wagtail to pretend it's following the filesystem model.

**Comment by jangondol** [comment]
@gasman You're right, my mind is often wrapped around the filesystem model (perhaps because I like static sites and things they let you do, e.g. [when paired with IPFS](https://news.ycombinator.com/item?id=10228293)). Looks like I'll need to resort to some workarounds to be able to keep using Wagtail... ;-)

**Comment by coredumperror** [comment]
I second this request for an option to not automatically redirect to trailing slash URLs. I personally think they're ugly, and the fact that setting `APPEND_SLASH` to False _doesn't work_ is pretty confusing.

**Comment by gasman** [comment]
Implemented in #2298.

**Comment by coredumperror** [comment]
That's great!
