### ISSUE TITLE
Image is not uploaded properly.

### ISSUE THREAD

**Issue by RatanShreshtha** [torchbox/wagtail#2100]
I am trying to add images in my post but whenever I try to do that the image is not uploaded.
I followed Integrating Wagtail into a Django project part of tutorial.
I am currently developing on my local machine and I am using django 1.9.1 and wagtail 1.3.1, I am on ubuntu 14.04 and I am using chrome browser.

![screenshot from 2016-01-12 01 16 35](https://cloud.githubusercontent.com/assets/10801618/12244704/eb15dcee-b8ca-11e5-857c-381fa31e2a9a.png)

This is the output.

**Comment by gasman** [comment]
If you right click on the broken image and click 'Inspect', what's the image URL?

**Comment by RatanShreshtha** [comment]
URL is
/media/images/DSC00149.max-165x165.jpg

**Comment by gasman** [comment]
Thanks - the URL indicates that the image has been successfully uploaded and processed, so the problem is probably with serving the image back to the user.

Looking at the documentation again, it seems that we might be missing a step here - please can you try making the change to `urls.py` as described here:
https://docs.djangoproject.com/en/1.9/howto/static-files/#serving-uploaded-files-in-development
and let me know if that works? If so, I'll update the documentation accordingly.

**Comment by RatanShreshtha** [comment]
Thanks

Now its working fine.

**Comment by ivan-vilches** [comment]
i have same problem how did you fixed?
