### ISSUE TITLE
Make the wagtail's tail longer!

### ISSUE THREAD

**Issue by dandavison** [torchbox/wagtail#211]
I like the name and the fact that a wagtail is the icon! Just one nit: the icon is clearly intended to depict a wagtail of the genus *Motacilla*, but a characteristic feature of those birds is their long tail, and the icon has a decidedly short tail (in fact it has more the shape of a *Parus* tit).

![image](https://cloud.githubusercontent.com/assets/52205/2812738/42c3933c-ce6c-11e3-8c1a-87063820cabc.png)

![image](https://cloud.githubusercontent.com/assets/52205/2812741/7495ac38-ce6c-11e3-8fc7-8a651f51c223.png)

**Comment by davecranwell** [comment]
Wagtail is receiving ongoing design updates as we find time to do them, a design refresh is planned but with no firm date as yet. Ultimately this issue is subjective with no good route to closure (any new logo could be subjectively thought to be equally un-wagtail-y) so we'll close this for now to help manage issues with a stronger story.
