### ISSUE TITLE
"I forgot my password" doesn't remind you what your username is

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#2240]
The flow is like this:

1. Failing to log in
2. Click "I forgot my password"
3. It has you enter your _email address_
4. It emails you a link to create a new password

Never in this does it help you if you forgot your username, or indicate what your username is.

I think the solution is to also include the username in the confirmation email.

EDIT: Alternatively, disallow users from creating usernames with the @ symbol in them, and allow people to log in using their email addresses.

**Comment by heymonkeyriot** [comment]
This is very similar to an issue  raised by @kiwimind at #722. 

I presume the reason wagtail currently doesn't echo the username is because there could be multiple users attached to the same email.

I think your suggestion `Alternatively, disallow users from creating usernames with the @ symbol in them, and allow people to log in using their email addresses.` would make a lot of sense. It's a similar flow to Twitter or Github and gives the most simple experience for the user. The downside is (as mentioned in #722) that it would require each user account to have a unique email address.

**Comment by gasman** [comment]
As mentioned on #722, Wagtail needs to be able to integrate into existing Django projects and authentication systems of varying degrees of esoteric-ness (including things like LDAP, although those are a moot point here because the developer ought to have disabled Wagtail's reset/change password features for those), so we can't impose any policies on usernames/logins ourselves.

Customising the user model to use the email address as username is in fact a common setup, and one that Wagtail supports (#1388). The open question in #722 (which we should really make a decision on...) is whether our default project template setup should do this - my feeling is no, as per @nealtodd's reasoning in https://github.com/torchbox/wagtail/issues/722#issuecomment-76389301.

Re the main suggestion here - I don't think the 'multiple users with the same email address' scenario is a blocker here, because in order for the password reset to work at all, Django must have some sort of mechanism for resolving the entered email to a specific user record (even if that mechanism is just 'choose a matching user randomly'). So, +1 for adding the username to the email (subject to a check that the user model actually *has* a username that's distinct from email).

**Comment by timheap** [comment]
The reset password functionality in Django finds all users with a matching email, and emails each of them in turn.

Adding the value of the USERNAME_FIELD to the email would be a very helpful addition. Even if the email address is the USERNAME_FIELD, I think echoing it useful. It shows the user exactly what they need to enter to log in, once they have reset their password.

**Comment by heymonkeyriot** [comment]
I agree that I think echoing the USERNAME_FIELD would be really useful. And I think the password reset functionality being the way that @timheap describes would I think deal with @nealtodd 's concerns in #722 .

**Comment by tomdyson** [comment]
@froztbyte one for you?

**Comment by froztbyte** [comment]
Yeah, +3 (or 3rd +1) for the suggestion as per @timheap. I'll have a PR with a suggested fix up shortly.

Am I correct in saying it looks like the mail template only has the one textfile `wagtail/wagtailadmin/templates/wagtailadmin/account/password_reset/email.txt` provided?
