### ISSUE TITLE
Why is the root page part of the database?

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#2351]
Was just having an issue getting a dev site up. Spent some time researching treebeard and wagtail pages to figure out why.

Turns out, the root page had `numchild` set to `1` in the database even though it didn't have any children. This was making treebeard error out because it was trying to traverse it like a branch. Setting it back to `0` indeed let me save the page.

I could make some guesses why this happened. But mostly I wonder if this situation is more preventable when the root page isn't part of the database. Wouldn't that be better, anyway? It seems like something that should be immutable from the perspective of a database.

Wondering if you could hard-code the root page as an instance of MP_Node.

**Comment by gasman** [comment]
The immutable root node wasn't part of Wagtail's design from day one, but it was added very early on when it was apparent that it would solve a lot of architectural issues (and not having it would have created major headaches for development):

* It ensures that all "real" pages have a well-defined concept of parent page, so that we don't need separate code paths for "add a page at the top level" versus "add a page as a child of X" (which would in turn mean different URL endpoints and tedious if/else switches whenever we want to output an "add page" link, and lots of edge cases that would be hard to catch in tests);
* It provides a way to set up permission rules that apply to the whole tree;
* it stops developers from painting themselves into a corner when they discover that the (real, viewable) page they set up as the root page should actually be further down the tree after all (for example, their project grows from a single-site installation to multiple sites).
