### ISSUE TITLE
Setting a page's go_live_at seems to have no effect

### ISSUE THREAD

**Issue by jaroel** [torchbox/wagtail#2366]
Either setting the go_live_at date on a page doesn't work, or I completely misunderstand it.
This is what I expected to happen:
1. I've got a concept page and set the go_live_at date.
2. I run manage publish_scheduled_pages (after the go_live_at date)
3. The page is published.

What happened was:
1. I've got a concept page and set the go_live_at date.
2. I run manage publish_scheduled_pages (after the go_live_at date)
3. The page is still concept.

The publish_scheduled_pages script checks PageRevisions.approved_go_live_at, but that isn't set when Page.go_live_at is set.
My guess is that Page.go_live_at should have been passed into Page.save_revision on https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/views/pages.py#L286.

Side note: unpublishing works as a charm!

**Comment by kaedroho** [comment]
The ``Page.go_live_at`` field does nothing, It looks like it was just added to implement the UI. As you've found out, the field you should be using is ``approved_go_live_at`` on ``PageRevision``

There's a proposal to remove it here: https://github.com/torchbox/wagtail/issues/771

**Comment by jaroel** [comment]
Here's a workaround:
```python:
class CampaignPage(wagtail.wagtailcore.models.Page):
    def save_revision(self, *args, **kwargs):
        if 'approved_go_live_at' not in kwargs:
            kwargs['approved_go_live_at'] = self.go_live_at
        return super(CampaignPage, self).save_revision(*args, **kwargs)
```

**Comment by gasman** [comment]
Hi @jaroel - it sounds like you might have been misled by Wagtail's terminology here. When you set a page's go-live date, you still need to hit 'publish' in order for it to take effect - saving it as draft is not enough. (It would probably make more sense for the "publish" option to be labelled something like "approve for publication" in this situation...) Wagtail will then return a response like "This page has been scheduled for publication on [date X]", and the page will become public on that date as expected.

The publish_scheduled_pages task intentionally doesn't touch pages with 'draft' status, because that would make it too easy to publish unfinished content by accident (e.g. an editor creates a new page with a go-live date set for a month's time, and fills it with placeholder content intending to complete it later - but then forgets to update it before the go-live date comes round). On multi-user setups, it would also potentially provide a way to bypass the moderation process.

**Comment by jaroel** [comment]
Hi @gasman - thanks for reply, much appreciated!
I'll close this issue, as it isn't really a bug.
