### ISSUE TITLE
Can't delete user

### ISSUE THREAD

**Issue by Luperi** [torchbox/wagtail#2371]
Why can't I delete users from wagtailadmin area, also if user logged in has delete permission on User model?

**Comment by alexgleason** [comment]
Good point. I think this will need some design/UX work, as we need to determine what should happen to existing content owned by the user when after the user is deleted.

WordPress gives you a radio box on the confirmation screen asking if you want to transfer all content to a different user or to erase associated content entirely.

**Comment by gasman** [comment]
On all models that have a concept of ownership (Page, Image, Document...), we have 'owner' set up as a nullable field (because otherwise you'd have to invent a fake user account when doing automated data imports). Assuming we've got those fields set up properly with `on_delete=SET_NULL`, then, there should be no problem with keeping the user's content around. (I can't think of any case where you'd actually want the content to be deleted when removing a user.)

I think a standard delete confirmation screen will do the job here. Not sure why we don't have one - just an oversight, I guess.

**Comment by Luperi** [comment]
@gasman No chances to see this feature in Wagtail 1.5?

**Comment by gasman** [comment]
@Luperi There's plenty of chance to see it in 1.5, assuming someone implements it :-) I can't promise to work on it myself, as there are lots of other high priority items to get through, but that shouldn't stop someone else from working on it.

**Comment by vincentaudebert** [comment]
Oops! Hold on on this one please. I totally missed the existing PR and fixed the issue in quite a different way. 
From what I get the existing PR "only" adds the delete button on the edit page. I added it in the listing too.
I will compare my code and the existing PR tomorrow (NZ time) and try to keep the best from it (especially the tests).

Sorry about this :s

**Comment by gasman** [comment]
Completed in #2523.
