### ISSUE TITLE
Error on new installation without custom page models

### ISSUE THREAD

**Issue by timorieber** [torchbox/wagtail#2428]
I think this is related to #2267. I came across this problem two days ago with wagtail 1.4.1 and the patch by @timheap applied locally and it persists with wagtail 1.4.2.

Currently it is not possible to start with a new wagtail project where only the base ``Page`` class is present. Trying to run any of the management commands (like ``python manage.py migrate``) produces the following error:

```
File "/my/path/lib/python3.3/site-packages/wagtail/wagtailcore/models.py", line 561, in check
    if not issubclass(cls.base_form_class, WagtailAdminPageForm):
AttributeError: type object 'Page' has no attribute 'base_form_class'
```

After adding own page models and migrations all works fine.

**Comment by timorieber** [comment]
It seems that this is only a problem with sqlite. If I configure wagtail to use postgres locally I'm not able to reproduce the error.

**Comment by gasman** [comment]
Hi @timorieber - I'm unable to replicate this on Wagtail 1.4.2 using a fresh `wagtail start` project with the `home` app removed:

	pip install "wagtail==1.4.2"
	wagtail start issue2428
	cd issue2428
	rm -rf home
	vi issue2428/settings/base.py  # remove 'home' from INSTALLED_APPS
	./manage.py migrate
	./manage.py runserver

Please can you re-test with Wagtail 1.4.3?

**Comment by timorieber** [comment]
I'm going to re-test within the next few days.

**Comment by timorieber** [comment]
I'm able to reproduce the error with Wagtail 1.4.3 following these steps:

```
pip install "wagtail==1.4.3"
wagtail start issue2428
cd issue2428
rm -rf home
rm -rf search
vi issue2428/urls.py  # remove 'search'
vi issue2428/settings/base.py  # remove 'home', 'search' and 'wagtailforms' from INSTALLED_APPS
./manage.py migrate
```

I removed `home`, `search` and `wagtailforms` consecutively, after each step trying to reproduce the error.

Normally I start with a even more thinned out configuration like this:

```
INSTALLED_APPS = (
    # Own apps
    #"mynewapp",

    # Wagtail apps
    "wagtail.wagtailredirects",
    "wagtail.wagtailsites",
    "wagtail.wagtailusers",
    "wagtail.wagtaildocs",
    "wagtail.wagtailimages",
    "wagtail.wagtailsearch",
    "wagtail.wagtailadmin",
    "wagtail.wagtailcore",

    # Wagtail dependencies
    "modelcluster",
    "taggit",

    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
)
```

**Comment by dirtycoder** [comment]
Hey @gasman, I was able to reproduce the problem, I'll take a look at it.

**Comment by dirtycoder** [comment]
So, as far as I can tell, what is going on is this:

During the initiation of the `wagtailforms` app it imports the `wagtail.wagtailadmin.edit_handlers` module, which as a side effect adds to the `Page` model the default values for `base_form_class` and `get_edit_handler` function.

I think I'll add two verifications during the `check` for the `Page` model, and if the default value is not set, I'll set it there.

PS: I'm not sure if it's the correct way to solve this.

**Comment by gasman** [comment]
Thanks for the investigation and the PR, @dirtycoder!

Setting default values fixes the immediate error, but I think the deeper problem is that this code https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/models.py#L577-L596 doesn't really belong in wagtailcore at all. `base_form_class` and `get_edit_handler` only exist for the purpose of constructing the wagtailadmin edit forms, so we generally try to keep that logic out of wagtailcore - that's why we have the whole "dance" where we only set those properties in edit_handlers.py. (In principle, it should be possible to use wagtailcore independently of wagtailadmin.) We should move those checks to wagtailadmin instead - I'll make a PR to do that now.

**Comment by dirtycoder** [comment]
@gasman sure!

I'd done this without proper knowledge about the code base but it already looked like a far from proper fix, and after your comment in the form submission issue, well, then I got the confirmation that this was wrong. haha

I haven't tried to make more progress on this again because I'm having a hard time configuring new hardware at home.
But thank you for investing the time to describe what is wrong and why, I really appreciate it.
