### ISSUE TITLE
Adding Data directly to a stream field

### ISSUE THREAD

**Issue by colinfrankb** [torchbox/wagtail#2462]
I know this is not the place for questions, but its code related, so I thought it would be relevant.

Why when I create an instance of a type that inherits from Page, and I append data manually to the stream_data array, do I have to use a tuple, where as when I get an existing instance from the database I have to use a dictionary.

```
page = models.ArticlePage(title='Great Article')
page.body.stream_data.append(
    ('page', other_page_instance)
)
```

### VS

```
page = models.ArticlePage.objects.get(id=1)
page.body.stream_data.append(
    {
        'value': 1,
        'type': 'page'
    }
)
```

**Comment by gasman** [comment]
Hi @colinfrankb - see the explanation here: https://groups.google.com/d/msg/wagtail-developers/DcyRWqRZncQ/1qYUKyDoCwAJ

(In short: stream values have to have a JSON-compatible representation and a Django-templating-friendly one, and converting between them can involve extra database lookups - so for performance reasons the StreamValue object keeps hold of whichever representation it started off as, and only does the conversion at the point where you retrieve an element from the list, using `page.body[0]` or similar.)

You shouldn't really be writing to `stream_data` - firstly because it's an internal property, and secondly because `StreamValues` are intended to be immutable values. The 'official' way to write back to a stream field is to construct a new list of tuples and assign that to the field:

    page.body = [
        ('page', my_other_page),
        ('paragraph', '<p>hello world</p>'),
    ]
