### ISSUE TITLE
Refactor admin generic views 

### ISSUE THREAD

**Issue by Morozzzko** [torchbox/wagtail#2482]
Hello everybody.

Recently I've been working on an app that uses Wagtail admin for CRUD interface. The lack of documentation on this topic made me read source code of Wagtail, where I found some issues which I would like to address.

## Lack of consistency in Wagtail modules
Some Wagtail modules use generic views (`wagtailadmin.views.generic`) and some are not. You can easily tell if a module uses generic views if it doesn't have a search panel. A lot of Wagtail modules (e.g. `wagtailusers`, `wagtailredirects`, `wagtaildocs`) use view functions instead which brings an inconsistent experience for both users and developers.

**Possible solution:** refactor the modules to work with class based views instead. 
**Things to consider:** 

* Some features some as search, AJAX, pagination and ordering are missing and have to be implemented
* Also, some pages might not need search and AJAX, so perhaps a mixin would be nice

## Interface

Django provides us with a number of built-in generic class-based views for different tasks. Currently, Wagtail admin generic views inherit from `View` and provide their own implementation for the common tasks: index (list), create, edit, delete. This design keeps the views as minimalistic as possible, yet has its own downsides. 

The main issue here is naming. The following table shows what I mean:

| Django view | Wagtail view|
|-----------------|------------------|
| ListView | IndexView |
| CreateView | CreateView |
| UpdateView | EditView |
| DeleteView | DeleteView | 
| DetailView | N/A |

If you wish to replace ```wagtail.wagtailadmin.views.generic``` with ```django.views.generic``` (or vice versa) you'll most likely fail.

The first reason is class naming, which is can be resolved quickly by updating imports.

But there is another thing. By default, Django classes use `pk` as a kwarg for getting an object, while Wagtail prefers `instance_id`, which means you have to update your `urls.py` as well.

Example:
```python
urlpatterns = [
    url(r'^foo/(?P<id>\d+)/$', view=MyDetailView.as_view()),  # works for Django 
    # url(r'^foo/(?P<instance_id>\d+)/$', view=MyDetailView.as_view()),  # works for Wagtail 
]
```

Practically, the problem is that Django and Wagtail generic views are not interchangeable.

**Possible solution:** 

* rename `IndexView` into `ListView` and `EditView` into `UpdateView`
* in order not to break everything.  add `DeprecationWarning` if people try to use IndexView or EditView
* rename `instance_id` to `pk` or allow either of those fields; raise `DeprecationWarning` if `instance_id` is used
* use Django mixins and generic views

**Comment by gasman** [comment]
Hi @Morozzzko,

You're right that the use of view functions in `wagtailimages`, `wagtaildocs` etc isn't ideal, and it's something that we're keen on fixing. `wagtailadmin.views.generic` was developed as a way to minimise the amount of code duplication that happens when we add new CRUD views, and over time we hope to extend its functionality (with search, pagination and so on) so that the existing modules can be ported to it.

(On the subject of adding new CRUD interfaces to Wagtail, you may be interested in the new `wagtail.contrib.modeladmin` module coming in Wagtail 1.5: http://docs.wagtail.io/en/latest/reference/contrib/modeladmin.html. As this started out as an independently-developed package, it doesn't use `wagtailadmin.views.generic` either, but we hope to combine the two efforts so that modeladmin ultimately becomes a thin wrapper around `wagtailadmin.views.generic`.)

I'm not particularly keen on adopting Django's CBV hierarchy - I find that they're a bit over-engineered, and the complexity they add seems to outweigh any benefits they provide. I think we're going to have a big enough task converting our apps to CBVs of our own design, without the extra burden of adapting them to Django's patterns too.

I think converting everything to CBVs is going to be a long-term, incremental process, and for that reason I'll close this ticket, as it's not really a task that can ever be considered 'done'. However, I'm happy to continue the discussion either here or on the [Wagtail developers list](https://groups.google.com/forum/#!forum/wagtail-developers), and we'd definitely welcome any pull requests that take us towards that goal.
