### ISSUE TITLE
Keyerror when sending password reset email

### ISSUE THREAD

**Issue by kutenai** [torchbox/wagtail#2486]
When sending a password reset email, I'm getting an internal error

I'll just share the raven error - hopefully that doesn't review all of the site secrets (probably does)

https://app.getsentry.com/share/issue/37343334302e313233323439393235/

**Comment by gasman** [comment]
Hi @kutenai,

The error shown here seems to be a failure while rendering the 500 error template. I suspect what's happening here is:

* an error is happening at the server level (e.g. unable to connect to the SMTP server) while sending the email
* as part of the error handling, Django tries to render the 500.html template to send back to the user
* 500.html is extending your base template, which includes the `{% wagtailuserbar %}` tag
* `{% wagtailuserbar %}` expects to find a `request` variable in the template context, but there isn't one (because this is an error response rather than a standard template response)
* this error is the one that ends up being thrown, masking the root cause (i.e. the SMTP error)

We should fix the `{% wagtailuserbar %}` tag so that it gracefully handles the lack of a `request` variable, and simply does nothing in that case. However, as a general rule I'd recommend that you make your 500 error template a plain standalone HTML file, rather than extending the base template - if the thing triggering the 500 error is a general failure (such as your database being down), then your site may well be 'too dead' to perform the usual tasks involved in rendering the page furniture (e.g. retrieving the list of pages to go in the site navigation).

**Comment by kutenai** [comment]
Thank you very much for the response. I can make a minimal base for errors.
