### ISSUE TITLE
Use of base Page class in views prevent subclass methods from taking effect.

### ISSUE THREAD

**Issue by woegjiub** [torchbox/wagtail#2492]
I was overriding the url method for my subclass, and have noticed that this takes effect in many places, but not everywhere.

In particular, https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/views/pages.py#L319

`page = Page.objects.get(pk=page.pk)`

Could be replaced with

`page = page.specific_class.objects.get(pk=page.pk)`

This feels counter-intuitive, and as though it goes against the norms of wagtail and django elsewhere.

I have noted #836, #1378, and #2022, but none of those address this exactly.

**Comment by gasman** [comment]
Thanks for pointing this out @woegjiub! In some cases (e.g. looping over large Page querysets) we avoid fetching the specific subclass due to performance concerns, but that wouldn't be an issue here.

I'll create a pull request for this, if no-one beats me to it... (for anyone who takes this on, it would be good to add a unit test for this that tries publishing a [`SingleEventPage`](https://github.com/torchbox/wagtail/blob/a0af3d6685b046acf4d46de5353c293d54371644/wagtail/tests/testapp/models.py#L245) and verifies that the confirmation message links to the expected custom URL)

**Comment by timheap** [comment]
[https://docs.djangoproject.com/en/1.9/ref/models/instances/#django.db.models.Model.refresh_from_db](Model.refresh_from_db()) could also be used here. It is a new method, added in Django 1.8.

**Comment by gasman** [comment]
Fixed in #2860
