### ISSUE TITLE
Initial inline panel forms don't have order field set. Causes crash on form submission

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#2494]
When you have an inline panel with the ``min_num`` attribute set, Wagtail will automatically add some blank forms when you create a new page.

These forms don't have their ``-ORDER`` set though, this means that if you add additional forms manually and don't alter the order before submitting, Wagtail will crash with the error ``TypeError: unorderable types: int() < NoneType()``.

**Comment by kaedroho** [comment]
Now getting ``KeyError: 'ORDER'`` errors. probably the same issue

**Comment by gasman** [comment]
I can't replicate this as described. The steps I'm taking are:

* Edit wagtaildemo's models.py so that EventIndexPage requires a minimum of 3 related links:

        EventIndexPage.content_panels = [
            FieldPanel('title', classname="full title"),
            FieldPanel('intro', classname="full"),
            InlinePanel('related_links', label="Related links", min_num=3),
        ]
* Add a new EventIndexPage
* Fill in the page title, intro, and titles for each of the initial related links
* Click 'Add related links' and fill in a title for the new related link
* Click 'Save' (also tried Publish)

The page then saves successfully.

**Comment by gasman** [comment]
Closing as unable to replicate

**Comment by nicoepp** [comment]
We recently experienced the same type of crash/error multiple times on forms with the `min_num` attribute set (using v1.13.1), but now I'm unable to replicate the crash. I just wanted to report that the issue still exists.
