### ISSUE TITLE
`allowed_parent_page_models` has no effect in the admin

### ISSUE THREAD

**Issue by akx** [torchbox/wagtail#2620]
Hey, it looks like `Page.allowed_parent_page_models()` has no effect in the admin's "add subpage" view.
Is this by design, or a bug?

For what it's worth, grepping for `allowed_parent_page_` in Wagtail only yields some results in tests...

We're running a slightly customized version of Wagtail (one that includes #2112), but it's based on 5158ee7aad594d3d9b8b7cd14c139094080466fb.

**Comment by akx** [comment]
It looks like [`Page.can_exist_under()`](https://github.com/torchbox/wagtail/blob/1496f18977a719419ef4c8399b668fae467c3e50/wagtail/wagtailcore/models.py#L944-L952) should just be augmented to look at `allowed_parent_page_models` too.

**Comment by gasman** [comment]
Hi @akx,
`Page.can_exist_under` doesn't check `allowed_parent_page_models`, because `allowed_subpage_models` already enforces the logic for both `subpage_types` and `parent_page_types`.

Are you overriding `allowed_parent_page_models` on your own page models? You shouldn't do that - you should set the `parent_page_types` attribute instead.
