### ISSUE TITLE
Don't wrap TableBlock in <div class="table">

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#2629]
The default rendering is a little too opinionated. It should just render a `<table>` element. We can determine how to target it with CSS on our own, by either using an existing parent element (ex. `main.content table`) or by overriding the template and wrapping the block in a div ourselves.

**Comment by gasman** [comment]
+1. The default StreamField markup wraps it in a `<div class="block-table">` already - which is itself not to everyone's liking (e.g. https://groups.google.com/d/msg/wagtail/E0fS5D5ZKa8/Weu52LfmAAAJ). Adding another one is surely redundant (and will just annoy the HTML purists further).

Putting this in 1.5 because it's quick and will spare us some backwards-compatibility hassle if we do it now...

**Comment by Proper-Job** [comment]
@gasman will you update the template?  If you need, I could put that into a PR for you.

**Comment by Proper-Job** [comment]
@gasman Actually I don't see a ```<div class="block-table">``` in the current implementation.
This is what the current implementation looks like:
![screen shot 2016-05-18 at 09 11 55](https://cloud.githubusercontent.com/assets/5182820/15350274/bc63a508-1cd8-11e6-90fc-4bbcaf2e816e.png)

**Comment by gasman** [comment]
@Proper-Job You get the `<div class="block-table">` wrapper if you use the StreamField's default rendering - i.e. you output it on the page as `{{ page.body }}` (and don't set a custom `template` property on the StreamField), rather than `{% for child in page.body %}{{ child }}{% endfor %}`.
