### ISSUE TITLE
Management command to update wagtail admin

### ISSUE THREAD

**Issue by dentemm** [torchbox/wagtail#2636]
I am having several situations where I need custom WagtailAdminPage(or Model)Form subclasses because I am updating model objects programmatically. I am doing this programmatic work using django management commands I have written to be able to alter some data. 

This made me wonder: would it be possible to develop a wagtail management command to update the admin in similar situations? This would reduce the need to write custom WagtailAdminPage(or Model)Form subclasses.

**Comment by gasman** [comment]
Hi @dentemm - can you give an example of the sort of updates you need to perform, and describe exactly what the proposed new management command would do?

**Comment by dentemm** [comment]
Hi @gasman,

thanks for replying! I am updating some data on my models (both Page models and Snippet Models), basically because the admin who is providing content made some mistakes. I wrote a management command to fix those errors, but they are not visible in the admin because no PageRevision object is being created I guess. 

So it would be useful to have some sort of solution to be able to reflect programmatic changes to the db in the admin. This is why I was thinking of a management command which could create a PageRevision object based on the current field values of a Page. An alternate solution be also be really helpful, of course!

**Comment by gasman** [comment]
Thanks for the clarification! I don't think it's going to be feasible for Wagtail to provide such a management command itself, since every update operation is going to be different and require custom code. What Wagtail could do, though, is provide a more streamlined method for performing field updates so that they take effect on both Page and PageRevision records - this is discussed in #1101.
