### ISSUE TITLE
Add a system check for inconsistent subpage_types and parent_page_types

### ISSUE THREAD

**Issue by mope** [torchbox/wagtail#2652]
Trivial example:

1. Page A has `subpage_types` set to [Page B]
2. Page B has `parent_page_types` set to [Page C]

-> Can't add sub pages to Page A

A very minor gotcha, but an inconsistency warning would still be a nice enhancement.

**Comment by gasman** [comment]
A couple of problems I see with this:

* What are the criteria for determining that a particular combination of `subpage_types` / `parent_page_types` is "inconsistent"? Saying "it's inconsistent if it results in being unable to add sub-pages" doesn't work, because there can be legitimate reasons for disallowing subpages.
* If we do come up with an answer for the above, but the criteria are too broad - i.e. it warns about a setup that is actually what the developer intended - how would a developer silence that warning? If we're going to start warning about things that aren't technically invalid but just look dubious, I think we need to approach that very carefully - otherwise people will get 'warning fatigue' and overlook more serious issues.
