### ISSUE TITLE
Documentation request: more `modeladmin` examples

### ISSUE THREAD

**Issue by jimr** [torchbox/wagtail#2712]
It's great that `modeladmin` got included in 1.5, but it would be great to see some more documentation, particularly in the form of examples. We're trying to do something relatively simple - make one of our model fields hidden and auto-populated from `request.user` - but can't figure out the "canonical" method (or even one that works satisfactorily). 

So far we've tried:
1. Override `create_view_class` and `edit_view_class` on our `ModelAdmin` subclass to views that reference a custom form where the field widget is overridden. This works, but the label is still displayed in the view.
2. Override `create_view_class` and `edit_view_class` on our `ModelAdmin` subclass to views that reference a custom form where `excludes` lists our field. This raises an error somewhere in the guts of Wagtail that expects that field to be present.
3. Similar to 1, override the views, override `get_initial` to return information from `request.user` into the form, and define `panels` on the models with a `FieldPanel('user', widget=HiddenInput())` which has a similar issue to 1 - it works, but the field label is still visible on the form.
4. Progressing from 3, remove the field from `panels` completely - this successfully removes the field from view (and from the form) but then we can't access `request` in order to auto-populate the value.

I'm not necessarily asking for the right answer for how to achieve what we need, more I wanted to point out that though having `modeladmin` is great, the indication in the docs that "the ModelAdmin class has a large number of methods that you can override or extend, allowing you to customise the behaviour", while true, has led us down several blind alleys in trying to achieve something pretty basic.

**Comment by ababic** [comment]
Hi @jimr. Thanks for the feedback. It's still early days for `modeladmin`, so this kind of feedback will help drive how modeladmin improves going forward. I certainly agree that the documentation could do with more examples, but as I'm sure you can appreciate, it would be difficult cover everything. Some cases (like yours above) span more than just modeladmin (hidden fields, custom forms, how they all work in combination with wagtail in general), so perhaps there's an argument for a different section of the documentation entirely?

I don't know that I can give a full solution to your problem, but the most 'django' way to hide a field from editors is to add `editable=False` to the field on your model, and both wagtail and modeladmin respect that, so you could then leave it out of your panels configuration completely without a problem.

I think it should then be possible to achieve the rest by overriding the `form_valid` method on both your custom add/edit views. You'd just have to [copy what it's doing currently](https://github.com/torchbox/wagtail/blob/master/wagtail/contrib/modeladmin/views.py#L162), and add some extra code to populate the field using the user from the request (available as `self.request.user` from within that method)

Hope that helps!

**Comment by jimr** [comment]
Thanks @ababic I'll see where I get with that approach - `form_valid` isn't one of the places I'd looked to hook into, so hopefully that'll sort me out. I feel bad asking for docs because usually I'd just write them myself, but in this case I'm not sure what to document :) I wonder whether including some `modeladmin` usage in the `wagtaildemo` project would be a good start to help others get to grips with the new features & functionality available?

**Comment by jimr** [comment]
Ok, so we got things working with the approach you suggested, @ababic, thanks!

I think I would still prefer to have the field in the form and hidden (populated via `get_initial_data`), however; doing so would mean I didn't need the `null=True` or any copy/paste overriding of functions. The only reason this approach didn't work was because the field label was left in the form (the input was hidden and set correctly). _Would you consider this a bug?_ If so, I'd be happy to spend some time looking into a fix.

Issue #2717 is something we encountered when trying to override the form on the view (approach number 2 above). If overriding forms isn't something that should work for whatever reason it may be worth noting that in docs also; the reason we tried was because it looked like it should work (the `modeladmin` classes inheriting from Django form views etc). Again, I'd be happy to write the docs myself, I'd just need to know it was intended behaviour :)

**Comment by ababic** [comment]
Hey @jimr. I would consider the label still showing for a hidden field as a bug, yes, and probably worth raising as it's own issue, if you wouldn't mind? I believe it's a 'panels' thing, though, rather than a modeladmin-specific one. 

I definitely agree with you about getting some guidance into the docs regarding overriding of model forms. If issues like #2717 and this are already cropping up, then it's clearly something that more people will run into similar difficulties in future. I guess it's a double-edged sword when you use common Django components. There are a lot of methods there that developers will be used to extending/overriding, which I would hope makes their lives easier in the main. But, Wagtail has it's 'edit handler' layer that complicates things when it comes to forms. I can't claim to know the full ins and outs of that myself, but @gasman may be able to offer some guidance about how we might possibly work around that in future.

An important thing to bare in mind here, is that `modeladmin` is still only handling the adding and editing for non-page models at this stage. That's mostly why the customisation available on the ModelAdmin class itself is focussed around 'listing' behaviour (that is the only view that is used consistently). In the future, I'd hope for the [page-management views](https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailadmin/views/pages.py) and other things in core to become class-based; which would make it possible for modeladmin to extend them, and offer a more consistent level of control for everything.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by gasman** [comment]
Now addressed by #2753 / #2902.
