### ISSUE TITLE
SiteMiddleware should catch database errors instead of causing 500 error

### ISSUE THREAD

**Issue by thenewguy** [torchbox/wagtail#2718]
I've just implemented some "ping" views for status checks.  Wagtail's SiteMiddleware does not catch errors that are thrown when the database is down so the status checks cannot continue.  It two I've found so far that it should catch alongside the DoesNotExist exception are DatabaseError and OperationalError.

**Comment by ababic** [comment]
Hi @thenewguy. I can certainly see the argument for wanting middleware to be as graceful as possible in the face of broken databases. But, as far as I'm aware, it's considered poor practice to catch errors that the code itself isn't responsible for. For guidance, I've been looking at the way [AuthenticationMiddleware](https://github.com/django/django/blob/master/django/contrib/auth/middleware.py#L16) and [CurrentSiteMiddleware](https://github.com/django/django/blob/master/django/contrib/sites/middleware.py#L6) handle things in Django, and I can't find any evidence of graceful handling of database operations within the processes they trigger.

I'm wondering if, for your needs, it may be better to create a custom `SiteMiddleware` in just your project, and use that instead of wagtail's built-in one?

**Comment by thenewguy** [comment]
@ababic I think your statement about catching errors that code isn't responsible is poor practice is spot on... but I think in this case the code is responsible for those errors.  It is attempting to communicate with the database without verifying the database is available first.  And since this is written in the middleware layer it breaks all other endpoints on the site, not just the wagtail endpoints.  I can write a custom `SiteMiddleware` but that doesn't seem like it would benefit the project as a whole.  Shouldn't it be a recommended best practice to monitor health check endpoints?

**Comment by thenewguy** [comment]
Also note that the `AuthenticationMiddleware` uses SimpleLazyObject(lambda: get_user(request)).  It doesn't actually query the database so it has no need to catch a database error.  All it does is attach a lazy object to the request.

**Comment by gasman** [comment]
I'd argue that if something is catastrophically wrong with your site (and a dead database would fall into that category), it's not really reasonable to expect every middleware to gracefully handle every possible failure case, just so that your status check page can cleanly return "something is catastrophically wrong". :-) Surely the fact that the status page is returning a 500 response ought to be enough to alert you to the failure?

**Comment by ababic** [comment]
> `AuthenticationMiddleware` uses SimpleLazyObject(lambda: get_user(request))

My mistake, sorry.

**Comment by thenewguy** [comment]
@gasman it sounds like you guys are vehemently against adding two exception classes to your try/catch block. I am not really sure why but I don't want to seem argumentative so I will let you close the issue if you like.  Personally, I think it is valuable to be able to use my status checks to determine that the database is down but the cache, storage, and celery runners are working just fine.  It certainly helps diagnose an issue quickly.  I don't "expect" every middleware to handle every possible failure case automatically... but I do like to help add missing cases when I find them

**Comment by thenewguy** [comment]
Would you be opposed to SiteMiddleware taking the same approach as AuthenticationMiddleware with the lazy object?  It would cut down a db query when request.site isn't used and punt this issue =)

**Comment by gasman** [comment]
@thenewguy Sorry, didn't mean to be so adversarial there! Generally, we want to minimise the number of different concerns and responsibilities that any given bit of code has - so it's not so much about avoiding an extra try/catch clause, as asking "should it be the middleware's responsibility to function correctly if the database is down?". If we decide it is, then we're essentially committing to preserving that behaviour in future, which adds an extra maintenance burden whenever we update that code in future.

Given that Django (apparently) doesn't consistently ensure that its own middlewares stay functional in the absence of a working database, my impression is that Django's own policy is "if the database is down, all bets are off", and so it's appropriate for Wagtail to follow suit.

**Comment by thenewguy** [comment]
@gasman, @ababic I have not been able to investigate in depth the complete line of django middlewares yet.  I do not remember seeing this problem on other django projects so I think (at least the default installed middlewares - or perhaps the installed ones were chosen selectively) do not have this problem.  I know `AuthenticationMiddleware` does not cause this problem as reported.  But one practical situation that started me down this path that I do not think you are considering is instance health checks are required for cloud deployments.  In the current state, if the database is taken offline for an update or backup or whatever reason then aws elasticbeanstalk will see the health check failing and terminate and replace all instances running wagtail (if the database is down for very long this can be a repetitive cycle).  Even for a simple view that returns HttpResponse("Healthy").  Is this not something worth considering?

**Comment by thenewguy** [comment]
So I've posted this to the google group instead as it seems like a more suitable discussion place https://groups.google.com/forum/#!topic/wagtail/nv1H2P9ZnEM
