### ISSUE TITLE
PageChooser field in admin view gives error on clicking button to link a page

### ISSUE THREAD

**Issue by rohan07** [torchbox/wagtail#2773]
Whenever I try to link a page using the PageChooserField in admin view, I get the error - "Uncaught TypeError: container.modal is not a function" in the console, which is from the file "modal-workflow.js". The modal never shows up and the same case is true for the ImageChooserPanel as well. Any idea what's wrong?

Thanks.

**Comment by gasman** [comment]
Hmm, can't really see what might be causing that - the `modal` function should be defined by /static/wagtailadmin/js/vendor/bootstrap-modal.js. What do you get if you enter `$('body').modal` on the console?

Also, what browser and Wagtail version are you running?

**Comment by gasman** [comment]
Closing for now due to lack of info - please update this ticket if you can provide the requested details.

**Comment by corysutyak** [comment]
I have encountered this issue as well.  From what I can gather, this issue is probably outside the scope of wagtail.

I am using the `django-address` package so that I have an auto-completing/geocoding address field and form widget on one of my snippets.  The widget that I'm pulling uses the Google Places API.  Any snippet I have that has an `ImageChooserPanel` and this address field is causing the issue `Uncaught TypeError:container.modal is not a function` when I click the `ImageChooserPanel` button.  

`$('body').modal` returns undefined.  Clicking the `ImageChooserPanel` button appears to append the modal div correctly.

I'm using Wagtail 2.0 and Chrome.  Any hunches on why this behavior would happen?  As far as I can tell, the JS loaded by Google isn't doing anything to inhibit the bootstrap-modal js.

Thanks for your time!

**Comment by gasman** [comment]
Hi @corysutyak,
You might have a better response asking [on Stack Overflow](https://stackoverflow.com/questions/tagged/wagtail) - we can't really do general troubleshooting here.
