### ISSUE TITLE
Wagtail Wikipedia page about to be deleted

### ISSUE THREAD

**Issue by ostrokach** [torchbox/wagtail#2815]
I created a Wikipedia [page](https://en.wikipedia.org/wiki/Wagtail_(CMS)) for Wagtail, because I wanted to add Wagtail to the [List of content management systems](https://en.wikipedia.org/wiki/List_of_content_management_systems). Now, this page is about to be deleted because it "does not meet notability guidelines". Django-CMS has a Wikipedia [page](https://en.wikipedia.org/wiki/Django_CMS), and it is *not* about to get deleted.

I am probably not the best person to edit the Wagtail page, since I have never used Wagtail. But if someone could add more information to it, I think that keeping that page up would go a long way to increase Wagtail exposure. I personally ended up on Wikipedia when looking over CMS systems.

**Comment by gasman** [comment]
Hi @ostrokach - thanks for your efforts and support!

I know of one earlier attempt to create a Wikipedia page for Wagtail, which also failed for similar reasons. Wikipedia generally disapproves of anything that looks like promoting a product - they take the position that it should become notable first and then get a Wikipedia page as a result, not use Wikipedia to gain exposure.

While we'd certainly _like_ to have a Wikipedia page, I don't think it'll be helpful for the Wagtail dev team to pursue that as a goal in itself... instead, we should focus on making Wagtail a better product so that it gains more usage and recognition (at which point, we'll have a much easier job persuading Wikipedia admins that the page should stay). Meanwhile, if there's interest from the wider Wagtail community in creating a Wikipedia page, we'd certainly support that - if you're interested in taking that further, I'd suggest dropping an email to the [Wagtail Google group](https://groups.google.com/forum/#!forum/wagtail).
