### ISSUE TITLE
wagtailcore.models.Site should probably inherit from django.contrib.models.Site

### ISSUE THREAD

**Issue by ppershing** [torchbox/wagtail#2840]
I thing it would make sense for Wagtail Site to inherit from Django Site. Right now Django's sites are independent of Wagtail's which makes a huge configuration mess for some third-party Django apps relying on Django sites but not Wagtail sites.

**Comment by gasman** [comment]
Hi @ppershing,
There's not enough detail here to evaluate this suggestion, sorry. If you can give a description of the specific problem you're having, and how inheriting from `django.contrib.models.Site` would fix it, then we'd be happy to consider this further.

**Comment by ppershing** [comment]
The specific problem is probably just more nuisance. 
Because Wagtail sites and Django sites are completely independent (and the latter is not visible in the Wagtail admin), it takes quite some time to track down issues where third party apps use "example.com" as a domain for various tasks. This happened to me with ```django-comments-xtd``` but I can see that the same thing will happen for anybody using ```django-registration``` or generally any other Django app that uses sites framework.

**Comment by timheap** [comment]
I have also experienced this problem. We solved it by writing code that syncs Wagtail sites to Django sites every time a Wagtail site is modified. Making Wagtail sites extend Django sites via MTI would ensure they are kept in sync, and third party apps will work as expected.

**Comment by pjmcdermott** [comment]
I'm not sure I would characterise it a mere nuisance! I must have spent the past day trying to work out why installing Wagtail impacted functionality on other parts of my site...

`wagtail.wagtailcore.middleware.SiteMiddleware` is fundamentally incompatible with `django.contrib.sites.middleware.CurrentSiteMiddleware` as they both set `request.site`. But the Wagtail `Site` object does not have the same field names as the Django `Site` object. Specifically, the Django `Site` model uses `domain` and `name`, whereas the Wagtail `Site` model uses `hostname` and `site_name`.

No warnings are given when the clash occurs--functionality just disappears.

At a minimum, the clash should be documented in the Wagtail installation notes at [Integrating Wagtail into a Django project](http://docs.wagtail.io/en/latest/getting_started/integrating_into_django.html). (also in the Puput docs.).

I'm note sure which `Site` model came first. The Django version is documented as far back as Django 1.7. I am also not familiar enough with Wagtail to have a view as to whether the two `Site` models are conceptually similar. They certainly look similar. But the Django sites framework is an official part of Django and is used by many other apps.

I would say the options are:

1. Make Wagtail `Site` object inherit from the Django Site object; or
2. Sync between the two objects using signals; or
3. Change the names of the properties on the Wagtail `Site` model to match those on the Django model and document a warning that the two bits of middleware should not be used at the same time; or
4. Add properties to the Wagtail `Site` object which match those of the Django `Site` object and pick up the relevant fields from the Wagtail object, again with appropriate documentation.

Personally, I am currently trying to work out how to globally monkey patch the Wagtail `Site` object for my project to achieve 4 above. I think the long-term solution is 1.

Given that this is a fundamental clash with the Django project, and a potential source of frustration and wasted time for **new** to Wagtail developers, which can discourage people from the project, it is not clear to me why this issue is closed.

**Comment by ababic** [comment]
This is a tough one for sure. 

While I agree that 1 is the cleanest out of all the proposed solutions, it's still not ideal. With multi-table inheritance, there are obvious performance-related issues to consider - particularly since `wagtail.wagtailcore.middleware.SiteMiddleware` attempts to populate `request.site` for each request. The two models also take significantly different approaches to solving the same problem - the updated model would have to store the same data two different ways... forcing us to override clean/save methods to ensure both are populated correctly. 

I feel like part of the solution should include the introduction of a new `Manager` with built-in caching to help mitigate the performance-related issues (similar to that [which Django's `Site` model uses](https://github.com/django/django/blob/master/django/contrib/sites/models.py#L27), and also the refactoring of `wagtail.wagtailcore.middleware.SiteMiddleware` to use a lazy object for  `request.site`, so that queries don't occur until they are needed.

**Comment by ppershing** [comment]
I am not sure I would call it two different purposes but whatever, I guess they should be kept in sync even if they are different. In the meantime, can we maybe explicitly warn users that they may need to edit also Django's sites? Best would be when you hit the save button.

**Comment by pjmcdermott** [comment]
@ppershing There is no need to warn users that they may to also edit the Django sites model, because the two pieces of middleware are straight out incompatible! They both set `request.site` and the model you get in the variable depends on the ordering of the middleware calls in `settings.py`. The warning in the docs. should be that you can't use both, and that if you are already using the Django sites model in your project expect to see any code or template references to the `domain` and `name` variables break.

**Comment by kakulukia** [comment]
A few days ago i was trying to use django allauth to integrate SingleSignOn into my wagtail project only to find out that wagtail doesnt play well and even breaks the Sites framework of Django.
After reading this conversation i understand that wagtail has some other needs, but why not rename the wagtail Site and thus not breaking 3rd party modules? @gasman?

**Comment by gasman** [comment]
The model name isn't the issue - Django can still distinguish them because they exist within different apps. The issue is that both Wagtail and Django have middlewares that try to set `request.site`, which is why I'm proposing to eliminate Wagtail's middleware in #3834.

**Comment by kakulukia** [comment]
Awesome plan! Im looking forward to that rewrite! Does the real-soon-now milestone refer to sometime this or early next year? I know that you cant promise anything .. just a mere guess?

**Comment by gasman** [comment]
@kakulukia real-soon-now roughly translates as: "no-one on the core team has resources allocated to work on this right now, but we know it's a pain point, and it will be prioritised whenever we next get a chance to choose something new to work on."

In practice, that kind of free choice doesn't happen very often - there are lots of pressures determining what we work on from day to day. Realistically, we won't get to it this year - we have a full quota of tasks for the Wagtail 2.0 release due in December (see https://github.com/wagtail/wagtail/projects/1). Early next year is possible, but it's much more likely to happen if someone outside the core team contributes it as a pull request.

**Comment by kakulukia** [comment]
Thx .. i might look into this myself then depending on the urgency of this feature

**Comment by okfish** [comment]
As i can see, the question is still open. 
Is there a way to get Django-Allauth work with Wagtail? Workaround, maybe, or other oauth packages could be suggested?

**Comment by rasca** [comment]
I need wagtail and allauth as well. Have you found any workarounds?

**Comment by kakulukia** [comment]
We postponed the feature. I’d didn’t have the time to look into the issue.

**Comment by mihow** [comment]
I agree that there should be a note in the docs under [Integrating Wagtail into a Django project](http://docs.wagtail.io/en/latest/getting_started/integrating_into_django.html) that says _"Wagtail is incompatible with any Django app that depends on the Django sites framework"_. I'd love to find a solution to this so that `allauth` is usable, but docs would be helpful in the mean time.

**Comment by gasman** [comment]
To be more specific, it's incompatible with `django.contrib.sites.middleware.CurrentSiteMiddleware` - projects that use the Django sites framework but not that specific middleware should be OK, I believe. Happy to add that to the docs (or accept a PR if someone else gets round to it first)...

**Comment by gasman** [comment]
PR opened to add this note to the docs: #5523

**Comment by gasman** [comment]
Current work on eliminating Wagtail's SiteMiddleware (as proposed in #3834) is open as PR #5332. Note that this might need updating to account for the `Page.dummy_request` changes in #5427.

**Comment by Ramblurr** [comment]
Does https://github.com/wagtail/wagtail/pull/5787 being merged mean that m Wagtail should be compatible with allauth?

I've been lurking for a few years now waiting for Wagtail to support allauth (or just some kind of oauth).

Is now the time to dive in and try to make them work together? Is master/current 2.9 in a stable enough state to try it out (on non prod deployments of course)?

**Comment by gasman** [comment]
@Ramblurr Definitely worth a try, yep. Master should always be in a usable state - I'd suggest trying the nightly build from https://releases.wagtail.io/nightly/index.html .

**Comment by thenewguy** [comment]
@Ramblurr They have always been compatible.

```
from django.contrib.sites.models import Site as ContribSite
from django.dispatch import receiver
from wagtail.core.models import Site as WagtailSite

@receiver(post_save, sender=WagtailSite)
def myhandler(sender, **kwargs):
    ''' create a new contrib site based on the wagtail site instance or update or anything you desire '''
