### ISSUE TITLE
Links that use unusual URI schemes

### ISSUE THREAD

**Issue by paul-apacio** [torchbox/wagtail#2906]
I'm having a little trouble with making links in the WYSIWYG with unusual uri schemes.  For example, one of our clients is currently trying to add a SIP link to a page: https://en.wikipedia.org/wiki/Session_Initiation_Protocol

This seems to get stripped at both a wagtail level and a hallo level.  Any clues or pointers to where I can modify the current link checking scripts to allow such schemes?

**Comment by gasman** [comment]
Hi @paul-apacio,
The list of allowed URI schemes is defined here: https://github.com/torchbox/wagtail/blob/7686290007126119a575430f3faa6cca4ebedc34/wagtail/wagtailcore/whitelist.py#L11

The "official" way to override this would be through the `construct_whitelister_element_rules` hook (http://docs.wagtail.io/en/v1.5.3/reference/hooks.html#construct-whitelister-element-rules), passing it an alternative rule for the `a` element - although you could probably get away with the quick-and-dirty approach of importing `ALLOWED_URL_SCHEMES` from that module and appending to the list.

A word of caution, though: are you sure this is an appropriate use of a rich text field? Usually when people run into limitations in the WYSIWYG editor's capabilities, it's because they're trying to build something structural that would be more effectively defined through proper structured data, as part of the site's data model. In this case, I'm guessing you're not simply inserting a SIP link in the middle of a paragraph of text - more likely, it's part of a contact record of some kind consisting of name, phone number, email and so on. If so, it would be more effective to define a `ContactPage` page type with dedicated fields for those things, or perhaps a [StreamField block](http://docs.wagtail.io/en/v1.5.3/topics/streamfield.html).
