### ISSUE TITLE
Trying to view live pages results in a 404 with the url ending in None

### ISSUE THREAD

**Issue by adamSiwiec** [torchbox/wagtail#2957]
I am new to Wagtail so this is probably an issue on my end. If someone could please direct me in the right direction, that would be appreciated!

**Comment by gasman** [comment]
Hi @adamSiwiec - please use the [Wagtail support Google group](https://groups.google.com/forum/#!forum/wagtail) for support queries.

**Comment by rifuso** [comment]
If somebody else encounters this problem following the tutorial in the documentation, this can happen if you create the blog index next to the Home in the Root instead of as a child of Home. The documentation reads "create a BlogIndexPage under the Homepage," but it would perhaps be better if it said "create a BlogIndexPage as a child of the Homepage."

**Comment by gasman** [comment]
Thanks @rifuso - that sounds like a good idea. Updated in 0629b6a8666c28b8d3b23b101feae5229c719f10
