### ISSUE TITLE
Old doc versions pollute search engine results

### ISSUE THREAD

**Issue by ipmb** [torchbox/wagtail#3003]
Like many developers, I typically start at Google when I am curious about a feature in Wagtail.

---

Usually, I get a link to an old version of the docs:

![wagtail nested blocks - google search](https://cloud.githubusercontent.com/assets/319156/18555083/b9144476-7b23-11e6-8370-06696711f6cf.png)

---

Those docs will have a link like this at the top of the page:

![freeform page content using streamfield wagtail 1 0b1 documentation](https://cloud.githubusercontent.com/assets/319156/18555191/2e9f4c2c-7b24-11e6-9345-0b6d0a3504d6.png)

---

Because the docs change structure over time, that link frequently 404s.

In contrast, when I search for things in Django, I always see a link to the most recent docs.

It'd be nice if via `robots.txt` or some other mechanism, only the most recent docs were indexed by Google.

**Comment by chimeno** [comment]
This is true, also happened to me.
I would say the best way to tackle it is putting a 
`<link rel="canonical" href="http://docs.wagtail.io/en/<last_stable_version>/<page_slug>">`
in the `<head>.`

I will try to make a PR within this week if nobody does it before.

**Comment by chimeno** [comment]
First, there is a RTD  page  about [Canonical](http://docs.readthedocs.io/en/latest/canonical.html), so RTD should be handling these things.

However, it seems they are not doing it well in wagtail's case:
The page http://docs.wagtail.io/en/v1.6.2/ currently has a canonical for http://docs.wagtail.io/en/v1.6.1/

Also there are some pages that no longer exists in the current docs structure, so their canonical link doesn't exists.

At first, I would try inside the RTD admin if there are some configuration that could fix it.

**Comment by gasman** [comment]
Thanks for the investigation @chimeno. Have just triggered a rebuild of the 1.6.2 docs, and it's now showing 1.6.2 as the canonical URL, as expected. Presumably 1.6.1 was shown there because 1.6.1 was the active version at the time the 1.6.2 docs were built...

I guess that means we have to rebuild _every_ version of the docs after releasing a new version - very annoying. (RTD probably assumes that everyone will set the active version to 'latest', so that the URL doesn't change - but that doesn't work for us, because 'latest' is the in-development version, and will often refer to functionality that isn't part of a release yet. There's a similar issue with 'stable' - I forget the details, but the branch/tag that RTD chooses as 'stable' is based on some unconfigurable magic.) And, of course, that still won't handle the issue of pages that have moved, which is the bigger problem.

**Comment by chimeno** [comment]
One possible workaround would be to disallow in robots.txt all pages not in /en/stable/ but I'm not aware if there are important implications after doing that.

Regarding moved pages, RTD gives a way of making redirects in their admin panel.
https://read-the-docs.readthedocs.io/en/latest/user-defined-redirects.html#page-redirects

I'm afraid I can't contribute to any of those.
Hope it helps.

**Comment by gasman** [comment]
Have now updated our release process docs with [some extra steps to ensure the canonical URLs get updated correctly](https://github.com/torchbox/wagtail/wiki/Creating-a-new-Wagtail-release#post-release). Not perfect, since there's apparently no way to rebuild old versions that have been deactivated, but hopefully it will help...

I've also added a bunch of redirects based on going through all docs.wagtail.io links that have been posted on StackOverflow, and ensuring they all point to somewhere useful in the current version of the docs. I'm sure that's not an exhaustive list, but probably the best we can do unless anyone fancies trawling through our Git history for all page moves we've done :-) We'll try to keep up the habit of adding redirects whenever we move docs in future.
