### ISSUE TITLE
"Choose another page" button on group permissions page is cut off

### ISSUE THREAD

**Issue by gasman** [torchbox/wagtail#3031]
Increasing the font size of buttons (#2985) has resulted in the text of the "Choose another page" button under Settings -> Groups -> Page permissions being cut off:

<img width="409" alt="screen shot 2016-09-27 at 22 43 07" src="https://cloud.githubusercontent.com/assets/85097/18893016/f9047864-8503-11e6-88ff-e2afeacf4807.png">

**Comment by gasman** [comment]
Oops, looks like this is specific to #3035 because of the extra column. Will fix it there...

**Comment by strindhaug** [comment]
BTW: if the design is dependent on an exact string length and font size, it will be almost impossible to translate well. When translating the length of a string could easily double (or halve) because of different word lengths and grammar in the other language. The layout should tolerate at least ± 50% string (ideally more) length change without breaking or overflowing for it to be easy to translate.

An added bonus is that if the design tolerates this, adding an extra column won't suddenly completely break the layout as well.
