### ISSUE TITLE
Live button url incorrect when using a reverse proxy and not a root path for the wagtail_serve view

### ISSUE THREAD

**Issue by Gagaro** [torchbox/wagtail#3056]
Hi,

I am currently using wagtail with the the wagtail urls not being on '/' but on 'wagtail/':

```python
url(r'^wagtail/', include(wagtail_urls)),
```

And I have my nginx configured so that `/` is actually `/wagtail/`:

```
location / {
        proxy_pass http://127.0.0.1:8000/wagtail/;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
    }
```

My issue is that the live button will redirect me to the site but with `wagtail/` appended.

I know how to solve it for me, but I'd prefer having an option somewhere to actually fix the issue. I have two idea for now, one would be a Django settings `WAGTAIL_SITES_ROOT_PATH` (which would be None by default and keep the current behaviors).

The other idea would be to add a field on the Site model (`root_path` or something) to get the root path but for each site. Maybe combining both of those would be best (the settings on the Site if present  or else WAGTAIL_SITES_ROOT_PATH` by default if not None).

For info, the added code would be there (removing the wagtail root path and changing it by the site root path): https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/models.py#L787

I'd prefer to have some inputs before working on anything. What do you think?

Thanks

**Comment by gasman** [comment]
Hi @Gagaro,

As far as I can see, your nginx configuration is not just incompatible with Wagtail's URL mechanism: you would have the same problems with a standard Django site. Essentially: you're trying to make it use different URL patterns for forward URL resolution and reverse resolution (i.e. you want it to recognise the `/wagtail/` prefix on incoming requests, but NOT include that prefix on the URLs it generates itself). As far as I'm aware, Django doesn't provide any mechanism for this - a Django site using your nginx config would not be able use Django's `{% url %}` tag or `reverse` function, for example.

(If I'm wrong, and Django _does_ provide this feature: we should of course investigate that, rather than inventing our own solution!)

You don't mention what you're trying to achieve with this nginx setup, but I'm going to take a guess: you're running multiple domains on the same Django installation, and you need a way to have a different urlconf for each domain? In the past, I've handled that by giving each domain its own wsgi instance and settings file (with `ROOT_URLCONF` set differently in each one). I won't promise that that's the best solution, but it's one possibility.

In any case: whatever problem you're trying to solve here, I'm sure that someone in the Django world has already solved it in a more Django-friendly way :-)

**Comment by Gagaro** [comment]
Indeed I try to have several domain on the same installation, but the domain would be dynamically created. So having one wsgi per instance wouldn't be possible.

I never used Django site framework so I didn't think about it as a Django problem. Looking at the Django site documentation, I don't see anything about domain. So I guess I'll have to implement something for myself.

I'll reopen this issue I find a proper way to do that in Django. Thanks for the help 👍 .
