### ISSUE TITLE
Model Site problem when integrating with django-allauth

### ISSUE THREAD

**Issue by fakegit** [torchbox/wagtail#3081]
Django-allauth need django.contrib.sites installed, and use the site model often.

But wagtail has its own site model, and has different fields with django's.

How to solve this?

**Comment by gasman** [comment]
Hi @fakegit - is there anything that prevents you from using both apps/models side by side?

**Comment by fakegit** [comment]
Exactly, no.
I just consider how to use one site model to solve this.
Finally, I tried to use both site model, make django's site just a copy of wagtail's.

**Comment by DevinCalado** [comment]
@fakegit Would you mind sharing how you managed to get django-allauth working with wagtail?  How did you override the django.contrib.sites with the copy of wagtail's sites app? Have you run into any issues after implementing this workaround?

@gasman We can't be the only ones who have tried to setup django-allauth with wagtail... When I run the application with both the django and wagtail 'sites' apps, I'm running into some issues in which I can't really explain exactly where the issue is happening.  Static files not loading when running the application on local dev server- but I'm not seeing any errors on the client or server logs.  Just appears to be some crossed wires between the two 'sites' applications.

**Comment by kakulukia** [comment]
id also like to know how to get both wagtail and allauth working side by side, but so far i had no luck - any advances on this regard since one year ago? @DevinCalado  did you get it to work in the mean time?
