### ISSUE TITLE
ListBlock's child block when rendered on the template has incomplete classname

### ISSUE THREAD

**Issue by mevinbabuc** [torchbox/wagtail#3142]
If I have a block with an attribute as ListBlock, when its rendered out in the admin, the class name is incomplete `sequence-member blockname-`; i.e it ends with a hyphen. The class name does not contain the block name.

```
class LinkGroup(blocks.StructBlock):
    links = blocks.ListBlock(LinkBlock())

    class Meta:
        label = "Link Group"
        icon = "link"
```

<img width="603" alt="screen shot 2016-11-07 at 7 33 07 pm" src="https://cloud.githubusercontent.com/assets/1276650/20060462/49407700-a521-11e6-9ae6-f8a39de9c37e.png">

On further inspecting the code, found out that the code `<li id="{{ prefix }}-container" class="sequence-member blockname-{{ block_type_name }}">` in the `sequence_member.html` refers to `block_type_name` which is not send from the backend (list_block.py) line `48`

```
        return render_to_string('wagtailadmin/block_forms/list_member.html', {
            'prefix': prefix,
            'child': child,
            'index': index,
        })
```

### Technical details

* Python version: 3.4.5
* Django version: 1.8.15
* Wagtail version: 1.6.2

**Comment by mevinbabuc** [comment]
This is important as we have Javascript written for the admin based on the blocks added or the values modified.

**Comment by gasman** [comment]
Hi @mevinbabuc - thanks for the report!

As far as I can see, the `blockname-*` class name is dead code that has never been documented or used by Wagtail. Unfortunately, I don't think there's a logically sound way of making it work, because it's based on a false assumption: that blocks always have names.

In fact, child blocks of ListBlock (such as the `LinkBlock` in your example) deliberately don't have names: normally names are assigned by the parent block as a way to distinguish between different child block types, but ListBlock doesn't need to do this (because there's only one possible block type), and so the `ListBlock(...)` constructor doesn't bother to provide a mechanism for passing a name. (If it _did_, it would probably look something like `ListBlock(link=LinkBlock())`... but the `link` identifier would be extra complexity that serves no purpose.)

Besides, I don't think we'd want to encourage situations where blocks are given different styling or behaviour based on block _names_, rather than definitions. That would mean that a block defined as:

    foo = MyBlock(some_option=True, other_option=False)

could potentially behave differently to:

    bar = MyBlock(some_option=True, other_option=False)

...which seems wrong. (OK, I can see that there's potential use for it within StructBlock, so that you can write logic at the structural level such as "either `foo` or `bar` must be filled in" - but I can't really see any equivalent for ListBlock / StreamBlock, where each block should basically be independent.)

For that reason, I think the best response is to remove the `blockname-*` classname completely. You can still attach a custom classname within the block definition, such as `ListBlock(LinkBlock(classname='link-list-item'))`.

**Comment by mevinbabuc** [comment]
yes I agree; I think we should remove it.
