### ISSUE TITLE
Security risk using mark_safe

### ISSUE THREAD

**Issue by shoefler** [torchbox/wagtail#3189]
A security risk exists when using the mark_safe() function which has the potential to expose Wagtail to cross site scripting.   The mark_safe() function says that the parameter is safe for client side output without using Django's automatic string escaping.  Using mark_safe() on an internally generated string is okay.  Using mark_safe() on variables which an external subject can manipulate or create poses a risk.  

A code scanning tool called Bandit blacklists mark_safe [here](http://docs.openstack.org/developer/bandit/blacklists/blacklist_calls.html).

mark_safe() is used 47 times in the code.  I am creating this issue as a placeholder to ensure the cases where mark_safe() is used are for valid use cases.  All uses should be reviewed.  If all mark_safe() uses are truly safe, this ticket can be closed.  Improper uses of mark_safe() should be fixed.

Without understanding the code well enough myself, I could not accurately determine if mark_safe() was used appropriately.  

I was initially questionable about line 29 in wagtailadmin/edit_handlers.py where html and script strings are marked safe.  
`def widget_with_script(widget, script):
    return mark_safe('{0}<script>{1}</script>'.format(widget, script))`

Line 24 in utils/widgets.py does the same.  
`out = '{0}<script>{1}</script>'.format(widget_html, js)`
`return mark_safe(out)`

**Comment by timheap** [comment]
`mark_safe` is dangerous when it takes potentially unsafe input from users. In `wagtailadmin/edit_handlers.py:29` and `utils/widgets.py:24`, the input is generated by Wagtail using templates that do not accept user input, and produces output that is safe HTML. `mark_safe` is appropriate and safe in this context.

**Comment by gasman** [comment]
Hi @shoefler - thanks for the report. We very much welcome analysis of Wagtail from a security perspective.

As you mention, `mark_safe` is not _in itself_ a security issue - it's a legitimate way of defining strings that are intended to be interpreted as HTML, and only becomes a security risk if it's used on unchecked user input. In the case of a developer-facing piece of software like Wagtail, this becomes more subtle since we need to distinguish between:

1) strings defined in Wagtail itself
2) strings supplied by the developer building a Wagtail site
3) strings supplied by administrators or content authors using the Wagtail CMS
4) strings supplied by an end user of the site built in Wagtail

We'd only consider 3 and 4 to be untrusted user input - the developer is inherently a trusted user (and it's fundamental to the working of Wagtail that they're able to use arbitrary HTML within the page templates and administrative interfaces they build).

(Some features, such as [RawHTMLBlock](http://docs.wagtail.io/en/v1.7/topics/streamfield.html#rawhtmlblock), allow content authors to insert arbitrary HTML - by using these features, the developer is implicitly considering content authors to also be trusted users. These features will always be clearly marked in the documentation and not enabled by default.)

I suspect that distinguishing between these cases is outside the scope of what can be done with an automated code scanning tool - typically we'd hope to catch any misuses of `mark_safe` as part of the code review we perform on all pull requests.

Unfortunately we don't have the resources to provide a rationale for each individual occurrence of `mark_safe`. If you're willing to put in the work of verifying these individually then that would be very much appreciated, but we'd ask that you only raise them as potential security risks if you have reasonable suspicion (based on following the flow of the code) that they can be triggered by users in category 3 or 4 above.
