### ISSUE TITLE
Add platform support for Google AppEngine

### ISSUE THREAD

**Issue by bhagyas** [torchbox/wagtail#35]
Since Google AppEngine supports python, I think it would be great to be able to run wagtail on AppEngine.

**Comment by davecranwell** [comment]
Please feel free to continue discussion of possible GAE support on the google group https://groups.google.com/forum/#!forum/wagtail

**Comment by tomdyson** [comment]
We're starting to look at this again, using MySQL. Salvador Faria has made some progress: https://twitter.com/salvadormrf/status/566995939089719296

**Comment by kaedroho** [comment]
It looks like our main challenge here would be that GAE doesn't support installing built packages. We need Pillow and libsass. PIL comes installed on GAE and that might work (Django 1.8 has dropped support for it though). Might have to look for a pure-python module for sass compilation though.

Other things that make me grumble (none of these are challenging, they just annoy me!):
 - You have to install all requirements locally (into the project itself). GAE does not use virtual environments or pip.
 - Latest version of Django is 1.5 and support for that is in "alpha" (https://cloud.google.com/appengine/docs/python/tools/libraries27). We could work around this by installing Django locally though.
 - They don't support Python 3

**Comment by gasman** [comment]
> We will have to find a pure python module for SASS.

Good luck with that :-/ #15

I think using offline compilation to sidestep the need for SASS on the production server is our best bet, although I'm not sure how feasible it is to insert that into the deployment process. (I seem to recall there's some issue with the architecture of django-compressor that makes it difficult to truly separate out the SASS compilation from the production server...)

**Comment by kaedroho** [comment]
I've actually come across that issue before. You can see a workaround here: https://github.com/torchbox/wagtail-template/blob/develop/Dockerfile#L23-L26

**Comment by tomdyson** [comment]
I wonder if we should revisit the tricky question of requiring SASS. Do the benefits for Wagtail admin stylers still outweigh the costs of

- tricky Windows support
- blockers / clunky workarounds for Google App Engine
- slower install times for everyone

?

**Comment by kaedroho** [comment]
I think it's worth considering sticking both the SASS and CSS in the repo. We would recompile it every time the styling changes.

I know @gasman and @davecranwell  would hate me saying that, and rightly so. But I think we should weigh it out against the costs that @tomdyson mentions. We actually do a similar thing for translations already.

**Comment by davecranwell** [comment]
Actually I would support putting compiled CSS into the repo, I've been
thinking this might be a solution for a while too.

One reason we've avoided this in the past was the concern that other
developers might compile their files with a slightly different of SASS,
creating minor differences where none really existed. This concern was
mainly voiced before we received our first PRs however the reality of the
situation is that (iirc) almost no one has edited any CSS for the
wagtailadmin.

To avoid compilation differences I think all we need is documentation
saying "you need version X". If someone submits a PR with loads of bogus
changes, it'll be plainly obvious and you just say "no, please recompiling
using X and resubmit". In fact by having both SASS and CSS in the repo, we
could always just compile it for them.



Head Of Front End Development
david@torchbox.com
Torchbox Ltd | 01608 638370 | http://torchbox.com

**Comment by timheap** [comment]
I second shipping compiled CSS instead of requiring libsass on the deployment server. If the styles are not dynamic, then they only need to be compiled to CSS when they are changed, and those compiled CSS changes committed with the SASS changes. A helper (`Makefile`, `gulp` task, shell command documented in the README, etc) could then be used to compile the SASS as required.

I came up with a solution that may interest you for a Django package I made, regarding the JavaScript files it needed. Shipping the package with minified JavaScript sources is a good idea, so that users of the package do not need to minify it themselves by extracting it from a virtualenv. However, committing compiled JavaScript assets was annoying, as the commit logs were needlessly noisy with the changes to the minified JS files. Additionally, making contributors minify the JavaScript files was going to be an ongoing battle, with possible version issues you mentioned above, as well as people just forgetting to do it. I came up with an alternative: Minify the JS files when packaging the application! This way, the files could be ignored in git, would always be fresh in any packaged version, and the compiling happens automatically. Something similar could be done for Wagtail: provide a script that compiles the CSS, and run that script when packaging Wagtail up or installing it through `pip install -e git+...` or other means. The compiled CSS would then always be current and correct, could be linked directly from the admin, and would not require libsass to be installed except when hacking on the styles or releasing a Wagtail build.

The package I was talking about is [django-formset-js](https://bitbucket.org/tim_heap/django-formset-js/src/c187bcf70a850133bbc156322cf8b7a4f46119a8/setup.py?at=master)

**Comment by davecranwell** [comment]
Yeah I wondered if that was a possibility - compiling the CSS only at the point of creating a new release. That doesn't really help people keen to experience the bleeding edge master, but you'd expect anyone doing that would be savvy enough to get SASS installed. It's just an issue of documentation.

**Comment by gasman** [comment]
I'd be much happier with the compile-on-release approach, if we can make that work.

Whatever approach we take, I'd like to see a proposal that details where the compiled CSS will go, exactly what settings need to change, how and when it determines whether to look at the compiled CSS in preference to the source files, and how we'll accommodate common developer and end-user scenarios such as (but not limited to):

* inserting custom CSS into the admin, for the rich text editor or [custom branding](http://docs.wagtail.io/en/latest/howto/custom_branding.html)
* switching an existing deployment from running off a PyPI release to running off Git
* setting up a developer installation
* making and merging pull requests that update CSS
* documentation for the above

**Comment by timheap** [comment]
@davecranwell: It should be possible to also override the `develop` command, which is what is run when doing `pip install -e path/to/wagtail`. There is likely to be one for installing via a git URL as well (very possibly the same command). As long as it is documented that you need libsass installed to hack on wagtail/run bleeding edge code, this should work.

@gasman: Your points are very valid, I completely agree that this would need some good documentation to be acceptable. Some initial thoughts:

* Inserting custom CSS into the admin would likely work the same, as long as you are not inserting SASS files expecting them to be compiled.
* If the `develop` command was also overridden to compile the assets on installation, all a user would have to do is install the SASS compiler and then install bleeding edge. The assets would then be compiled upon installation.
* Developer installations would just require the development dependencies (SASS compiler, sphinx, etc)
* Changes to the styles would just change the SASS source files, the CSS files would be ignored in git. Any pull requests would only contain changes to the SASS files.
* Documenting the above is essential for this to work, I agree.

**Comment by tomdyson** [comment]
Thanks very much for your input, @timheap. 

It's interesting that Bootstrap includes the compiled CSS in its repo. Their documentation for contributors makes it clear that CSS files shouldn't be submitted: 

https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#pull-requests 

"Do not edit bootstrap.css, bootstrap-theme.css, or bootstrap.js directly! Those files are automatically generated."

Could we do the same thing: keep generated CSS in the repo and only rebuild it (ourselves) when PRs are merged?

**Comment by salvadormrf** [comment]
I have been playing around and it is possible to run on Appengine
However there is some issues...
http://wagtaildemo.appspot.com/

I will create a repo with the configuration and instructions.

**Comment by merqurio** [comment]
That would be great @salvadormrf !!!

**Comment by johnbward** [comment]
Thanks @salvadormrf! This could be very helpful for me!

**Comment by salvadormrf** [comment]
I am currently on vacation, added the demo code here https://github.com/salvadormrf/wagtail_gae
It have have some changes, ill try to clean up in the following weeks.

**Comment by salvadormrf** [comment]
Updated the repo with more commands on how to run wagtail on Google App Engine SDK
https://github.com/salvadormrf/wagtail_gae

It is a combination of configurations to be able to run it:

- use a wagtail version with fixed mysql image filter issue
- use a google cloud storage wrapper for the uploaded files
- increases the max upload memory size, and removes TemporaryFileUploadHandler from upload handlers
- disables in-request compression of assets

**Comment by tomdyson** [comment]
Note MySQL support is now complete (in version 1.0): 

https://github.com/torchbox/wagtail/issues/541#issuecomment-86962302 

So, with @salvadormrf's help, we're getting close to a smooth experience for Wagtail on GAE.

**Comment by kaedroho** [comment]
We've added MySQL support and precompiled SASS. Is Wagtail now in good shape for GAE?

**Comment by salvadormrf** [comment]
Thanks @kaedroho, we have used Wagtail on GAE to generate a static website.
Currently I am working on a different project, but would be nice to check a few aspects.
- image upload (as far I can remember, there was some issues when uploading large files)
- app-engine auto-scaling (I was getting some blank pages after a few reloads, was fixed by setting the maximum number of connections per instance, however we don't know how well wagtail performs with  high load)

### django settings
```
# Removes TemporaryFileUploadHandler from upload handlers.
# (on Appengine we don't have access to filesystem)
FILE_UPLOAD_HANDLERS = ('django.core.files.uploadhandler.MemoryFileUploadHandler',)
FILE_UPLOAD_MAX_MEMORY_SIZE = 262144000 # the django default: 2.5MB
```

###  app.yaml
```
# Each App Engine instance cannot have more than 12 concurrent connections to a Google Cloud SQL instance. (Google App Engine Limits)
automatic_scaling:
  min_idle_instances: 1
  max_concurrent_requests: 12
```

**Comment by gasman** [comment]
@tomdyson What are our criteria for considering this 'done'? Does it require one of us to schedule some time in to get (e.g.) wagtaildemo running on GAE to confirm for ourselves that it works, or would it be reasonable to close this now and wait for other people to report AppEngine-specific issues?

(I guess there's a wider question here, about the extent to which we intend to formally support particular hosting platforms. If we're going to go as far as providing deployment docs for GAE, then logically we ought to do the same for other popular platforms such as Heroku...)

**Comment by gasman** [comment]
Closing as there are no *known* issues with Wagtail on Google App Engine at this point. That may well be more due to lack of people trying it, rather than the process being entirely bug-free, but the outcome is the same either way :-) Anyone encountering issues with Wagtail on GAE is welcome to open a new ticket for them.

**Comment by nimasmi** [comment]
Note also @potatolondon's efforts at https://github.com/potatolondon/wagtail-gae/, based on https://github.com/potatolondon/djangae.
