### ISSUE TITLE
from wordpress to wagtail

### ISSUE THREAD

**Issue by foxmask** [torchbox/wagtail#387]
Just a question ; is it planed to make a migration script that permits to migrate from wordpress ?

**Comment by iraycd** [comment]
I guess, Wordpress is not powerful or different from the way how wagtail Works since the introduction.
content_json / StreamField is a similar concept from Sr. Trevor Js.

I am trying to use wagtail for my blog.

I will try to make a plugin which is independent. Can you suggest which is the best content type in StreamField which is good to dump in all the wordpress content.

**Comment by gasman** [comment]
@iraycd I suppose it depends how clever you want it to be...

Wordpress allows you to use any HTML, without restrictions, so the most appropriate existing block type would be `RawHTMLBlock`. However, that's not a perfect fit, since Wordpress evidently performs some processing on the text (e.g. converting line breaks to `<p>` tags - maybe there's more that I'm not aware of). A neater solution would be to create a new block type (`WordpressHTMLBlock`?) that translates between the 'pseudo-HTML' source code seen in the backend and the real HTML rendered on the front-end, using a similar mechanism to `RichTextBlock`:

https://github.com/torchbox/wagtail/blob/v1.0/wagtail/wagtailcore/blocks/field_block.py#L232-269
https://github.com/torchbox/wagtail/blob/v1.0/wagtail/wagtailcore/rich_text.py#L179-191

The best option of all would be for your plugin to parse the HTML from Wordpress and split it into multiple StreamField blocks (e.g. `<p>first para</p> <img src="..."> <p>second para</p>` would be converted into a RichTextBlock, ImageChooserBlock and RichTextBlock) - this way, you're taking advantage of Wagtail's capabilities and adding the structure that Wordpress doesn't provide by itself. But that's probably a bit too ambitious for a first version!

**Comment by FlipperPA** [comment]
Interesting, I was just thinking through this issues today now that Wagtail is at 1.0. I've got a bunch of old content on my blahwg I don't want to lose. I'll take a look at the WordPress export format for starters, I've never given it more than a cursory glance.

**Comment by nkuttler** [comment]
I actually migrated my old WordPress content into Django somewhen in 2011. I used the XML export functionality of WordPress, and imported that into Django as raw HTML. The whitespace handling is done in a function called ``wpautop`` which I more or less ported to Python back then.

The real problem was that WordPress content uses things called shortcodes [foo id="5"] that can render anything from image galleries to custom markup. Shortcodes can be rendered from WordPress with ``do_shortcode()``, so an exporter could be written, or probably already exists. I chose to reimplement some of the shortcodes in Django and got rid of the rest.

All that being said, a generic import script for the xml export doesn't sound very doable to me, but covering the core WordPress built-in shortcodes, posts and pages does.

**Comment by FlipperPA** [comment]
I haven't made nearly enough progress, and shortcodes are going to be an issue, but here's a start in case anyone wants to contribute:

https://github.com/FlipperPA/wagtailpress/

I'm starting the import code with a pretty nice import I found in another CMS, Zinnia:

https://github.com/FlipperPA/wagtailpress/blob/master/wagtailpress/management/commands/wpimport.py

My initial goal is simply to be able to port my entire WordPress blog over to Wagtail, including blocks for MarkDown and Syntax Highlighting (from JS -> Pygments).

**Comment by gasman** [comment]
I don't think this can be meaningfully done at Wagtail's level of 'generic-ness', as Wagtail itself doesn't define what a 'blog post' actually is - it's better placed in a project such as [Puput](https://github.com/APSL/puput) which defines a specific blog post model.
