### ISSUE TITLE
Password reset request generates email with URL "example.com"

### ISSUE THREAD

**Issue by davecranwell** [torchbox/wagtail#841]
Received:
````
Please follow the link below to reset your password
http://example.com/admin/password_reset/confirm/NA/3x7-cfc1f37209f0c04d1ee1/
```
This time `BASE_URL` *is* configured, but as this view is from django.contrib this is perhaps due to some other missing setting. 

Related to #693 #826

**Comment by gasman** [comment]
`example.com` comes from Django's "sites" framework: https://docs.djangoproject.com/en/1.7/ref/contrib/sites/

Wagtail in general doesn't use the Django "sites" framework, but django.contrib.auth (which handles the password reset view here) does use it if available; if not, it falls back on RequestSite, which isn't particularly desirable either (it takes the domain name from the current request, which might not be directly usable e.g. if the site is behind a proxy).

The direct fix is to go to django-admin and configure the default Site record correctly; however, it's not really reasonable to expect Wagtail site administrators to do that, since Wagtail has its own partially-overlapping concept of site records and having both of them in use is a bit nasty. (In retrospect, we could probably have built Wagtail's sites mechanism on top of django.contrib.sites, but this isn't the place to reconsider that particular decision...) Instead, we'd be better off avoiding use of django.contrib.sites within Wagtail, and standardising on `BASE_URL` as used by the moderation emails.

Given that we're not enforcing the use of `BASE_URL` particularly well right now (as mentioned in #826, we don't even include it in the project template's settings file), we ought to take care to avoid breaking this for installations that *do* have django.contrib.sites correctly configured but don't provide `BASE_URL` (in which case their moderation emails will currently be broken, but we'd rather not make it more broken). So, I think the best plan is:

* Look for a `BASE_URL` setting
* Failing that, cobble together a URL from the result of [get_current_site](https://docs.djangoproject.com/en/1.7/ref/contrib/sites/#get-current-site-shortcut) (which will use either django.contrib.sites or RequestSite, depending on what's installed)
* Push the resulting URL into the password_reset view (using `extra_context`) and use that instead of the standard protocol/domain variables.

**Comment by labglo** [comment]
The default domain in the **sites framework** is called **example.com**. You'd have to change that.
You need to set to you domain name in admin sites.

**Comment by adrianrocamora** [comment]
This works well in hawthorn. Make sure to update both the example.com entry and the "display name"
