### ISSUE TITLE
image tag runs query on template load

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#865]
Theres a database query in the ``__init__`` method of ``ImageNode``:

https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailimages/templatetags/wagtailimages_tags.py#L42

This causes a query to be generated every time the template is loaded. The filter is not actually needed until the node renders though.

This can cause crashes if you are trying to load a template without a database (such as doing offline compression of assets).

**Comment by kaedroho** [comment]
Actually, thinking about this again. Does offline compression really render the template? If so, how does it do it without a context?

According to https://github.com/torchbox/wagtail/issues/541#issuecomment-75430982 this bit of code is also causing issues for MySQL users

**Comment by gasman** [comment]
django-compressor renders the template using a predefined context defined in settings: http://django-compressor.readthedocs.org/en/latest/settings/#django.conf.settings.COMPRESS_OFFLINE_CONTEXT

**Comment by kaedroho** [comment]
According to that doc: "when rendering the *contents* of ``{% compress %}`` template tags"

Will an {% image %} tag ever appear inside a {% compress %} tag?

**Comment by gasman** [comment]
Good point! I was under the impression that it rendered the entire template in order to discover where the `{% compress %}` tags were, but on closer inspection I see there's code to [step through the parse tree specifically looking for compress nodes](https://github.com/django-compressor/django-compressor/blob/develop/compressor/offline/django.py#L137) and just render those. My mistake!
