### ISSUE TITLE
Possibly incorrect hook names?

### ISSUE THREAD

**Issue by coredumperror** [torchbox/wagtail#870]
Going through the docs, I see two rather unusual hook names: `construct_wagtail_edit_bird` and `construct_whitelister_element_rules `. 

The first seems like a placeholder name that accidentally made it out of the alpha stage. Based on the docs, it seems like it should be called `construct_wagtail_userbar`.

The second seems like a straight up typo. I've never heard the word "whitelister" before. I'm pretty sure this hook should be called `construct_whitelisted_element_rules`.

Changing the names of hooks is obviously a major undertaking, since some code bases will have already implemented them. But adding the new names and deprecating the old ones for a few releases should be entirely possible. I'd be happy to do this in a pull request, since it's only a dozen or lines of code to change, but I don't really know how wagtail handles deprecating old APIs.

**Comment by zerolab** [comment]
Hi @coredumperror,

From what I can gather, the deprecation rules are as follows:
- A deprecation warning is added when the change is made. Corresponding release notes must added. See http://docs.wagtail.io/en/latest/releases/0.4.html#deprecated-features
- The features get deprecated two point releases later. e.g. http://docs.wagtail.io/en/latest/releases/0.6.html#all-features-deprecated-in-0-4-have-been-removed

You can find the DeprecationWarning and how they were used by viewing the history for `wagtail/utils/deprecation.py`. Specifically, look at https://github.com/torchbox/wagtail/blob/9eabdc374bd6176fc52573b6c10d2cfb7e1c5d44/wagtail/wagtailsearch/indexed.py

The one thing that stands out is that master has `RemovedInWagtail10Warning` rather than `RemovedInWagtail09Warning`. @kaedroho, please correct me if I am missing something obvious.

**Comment by kaedroho** [comment]
All features that were removed in 0.9 have been removed from master so theres no need for ``RemovedInWagtail09Warning``.
