### ISSUE TITLE
Page.specific and Page.specific_class are documented wrong.

### ISSUE THREAD

**Issue by coredumperror** [torchbox/wagtail#871]
The raw doc file for these two attributes of Page uses `autoattribute::` to bring in the docstring, but it's accidentally picking up the docstring for the `@cached_property` decorator, instead of the one for the `specific()` and `specific_class()` functions. 

There are comments just above these two functions which I think may be there to override this problem, but they don't appear to work. Every version of the docs that I can find has the same incorrect docstring for these two functions.

**Comment by gasman** [comment]
Looks like this has been [fixed in Django](https://code.djangoproject.com/ticket/23688) (as a result of someone spotting this exact bug in the Wagtail docs, no less!) - but only in the 1.8 branch, so it might be some time before the fix filters through to the wild.

@kaedroho, I see you tweaked the format of these docstrings in b0302d5e2d9daefc1a521b789a39b624a6099451 - did you succeed in getting them to output correctly? Does it require some specific Sphinx config that we're missing?

**Comment by gasman** [comment]
This is now showing correctly on http://docs.wagtail.io/en/v1.1/reference/pages/model_reference.html#wagtail.wagtailcore.models.Page.specific, presumably as a result of readthedocs upgrading to Django 1.8.

**Comment by coredumperror** [comment]
Great!
