### ISSUE TITLE
Download original image from image admin view

### ISSUE THREAD

**Issue by briknow** [torchbox/wagtail#873]
Users need to resize the same image right now when used in different situations. There is no way to download the original image from the image admin pages.

![sshot-2014-12-14- 12-17-18](https://cloud.githubusercontent.com/assets/5522412/5428884/58c241d6-838b-11e4-8f26-db507e98f4fa.png)

**Comment by davecranwell** [comment]
Original image file is now linked to within image editing interface, as of https://github.com/torchbox/wagtail/commit/9d7b26a5d4999f2e8bd161b5f3760f46f411eec9

**Comment by dperetti** [comment]
Unfortunately, the "original" image file is not the original it's a re-rendered image at the same size
My animated GIFs are turned into "image.original.png" PNG files ! 
Using Wand, my super optimised are re-rendered to the original size, but weighing 10 times as much !
Why not simply use the original file ?

**Comment by benebun** [comment]
> Using Wand, my super optimised are re-rendered to the original size, but weighing 10 times as much !
> Why not simply use the original file ?

I would also be interested in an answer. Also from a storage requirements perspective: original images are in /original_images/ but are also created  as .original. in /images/ but with the increased size as mentioned above by @dperetti.

**Comment by benebun** [comment]
FWIW: As @gasman argued in 2014 [here](https://github.com/wagtail/wagtail/pull/87#issuecomment-35879052) and [here](https://github.com/wagtail/wagtail/issues/128#issuecomment-37020610) original_images are not necessarily public.

@gasman My only nitpick that is left is would be that it is confusing for editors to display the original image size in KB on the top right and link the newly compressed image file on the bottom which will have a different image size. But that probably doesn't warrant a new ticket. I guess there is a reason for displaying the original KB size rather than the newly compressed original size there?
