### ISSUE TITLE
Absolute path references in external link url field

### ISSUE THREAD

**Issue by edrex** [torchbox/wagtail#901]
Sometimes you want to link to a local path that isn't a Wagtail page.

The correct way to do that is to use an [absolute-path reference](https://tools.ietf.org/html/rfc3986#section-4.2) such as `/foo/bar/`.

Currently it's not possible to create an internal link to a non-wagtail resource without including the domain and protocol. Including the domain and protocol is undesirable because it requires updating content if the domain changes (e.g., going from a staging to a production domain).

Suggested change: expand the validation regex of [URLValidator](https://github.com/django/django/blob/master/django/core/validators.py#L68) to allow for absolute paths.

Related: https://github.com/divio/django-cms/issues/1352

**Comment by edrex** [comment]
Alternative suggestion: allow manually specifying a path in the "internal link" tab.

**Comment by gasman** [comment]
Thanks for the suggestion - sounds like a good idea!

The first option (allowing local paths in the 'external link' tab) would be more natural, I think - internal links (in Wagtail's terminology) are stored as page IDs rather than URLs, so links to non-Wagtail resources don't really fit into this category.

**Comment by davecranwell** [comment]
Related #381

**Comment by gasman** [comment]
Fixed in #917.
