### ISSUE TITLE
Warnings with Django 1.7

### ISSUE THREAD

**Issue by SalahAdDin** [torchbox/wagtail#902]
Hi guys, i have the next warnings with django:
```
/home/tulipan/Proyectos/ADKM/lib/python3.4/site-packages/treebeard/mp_tree.py:102: RemovedInDjango18Warning: `MP_NodeManager.get_query_set` method should be renamed `get_queryset`.
  class MP_NodeManager(models.Manager):

/home/tulipan/Proyectos/ADKM/lib/python3.4/site-packages/robots/forms.py:7: RemovedInDjango18Warning: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated - form RuleAdminForm needs updating
  class RuleAdminForm(forms.ModelForm):
```

Why happens this issues?

**Comment by gasman** [comment]
Hi @SalahAdDin,

Both of these warnings are coming from third-party packages (treebeard and django-robots), and are not within our control.

The author of treebeard is usually very responsive to bug fixes and change requests, and I'm confident that this will be fixed in a future version of treebeard in advance of Django 1.8.

django-robots is not used by Wagtail, as far as I'm aware - presumably this is an additional package you've added to your project. Either way, it seems that this has [now been fixed](https://github.com/jezdez/django-robots/blob/master/robots/forms.py) (the 'fields' attribute is now specified) and the warning will disappear in the next release.

**Comment by SalahAdDin** [comment]
Yes man, i send a pull request for fix this warnings, thank you.
