### ISSUE TITLE
Question: Use alternative WYSIWYG editor.

### ISSUE THREAD

**Issue by SalahAdDin** [torchbox/wagtail#903]
Hi guys, i was looking for the WYSIWYG editor in wagtail and i saw that hallo.js hasn't updated in one year, we can think that is down. I like wagtail's WYSIWYG editor, is simple, softly, beautiful, but, he hasn't much tools, you know, than ckeditor, for example. CKEditor have much useful tools, tables for example, that hall.js hasn't but hallo.js is more beautiful than ckeditor.

I don't know if you want use ckeditor, or put many tools to hallo.js. CKeditor with wagtail's WYSIWYG editor will be great.

Also, i want as other question, i can replace wagtail's richtext with django-ckeditor's richtext? 
Thank you very much.

**Comment by gasman** [comment]
Hi @SalahAdDin,
We don't support any alternative WYSIWYG editors, because this would require heavily customising each editor to work within Wagtail - for example, using the Wagtail image library when inserting images. We've also made a deliberate decision to keep the WYSIWYG editor simple, and discourage the use of complex, structured HTML such as tables: if you need to display table-based data, it's much better to find a way to represent it in your site's data model, where it can be properly styled and queried, instead of being buried in a blob of HTML.

We're currently working on a new approach to 'mixed' content, described here: https://github.com/torchbox/wagtail/wiki/StreamField-specification . In this approach, all of the content types that are currently allowed in WYSIWYG content (headings, paragraphs, images, video...) would be separated into individual blocks, using the most appropriate interface for editing each one. This means that (over time...) Wagtail will become less and less reliant on WYSIWYG editors.

**Comment by dperetti** [comment]
I totally agree that the rich text editor should discourage anything complex.
However, I'd love to be able to use [Medium Editor](https://github.com/yabwe/medium-editor), which works beautifully and is very easy to tailor to your needs.
For example, It's very easy to [add a custom button](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/WALKTHROUGH-BUTTON.md) that lets you mark some text for example.
Such a rich text feature could even be enabled from RichTextBlock().

**Comment by SalahAdDin** [comment]
:+1:

**Comment by dchaplinsky** [comment]
Just in case: https://pypi.python.org/pypi/wagtailtinymce/

**Comment by fuzzy76** [comment]
> We don't support any alternative WYSIWYG editors, because this would require heavily customising each editor to work within Wagtail

That assumes you would implement all editors inside wagtail. I don't that was what is being suggested here at all. You would still only have one editor inside wagtail, but others could easily create add-ons for other editors (and do the integration).

I would hesitate to call anything without table (and source view) support out of the box for a CMS... Though I must admit StreamField looks promising.

**Comment by tomdyson** [comment]
> We don't support any alternative WYSIWYG editors, because this would require heavily customising each editor to work within Wagtail

This comment - from nearly two years ago - is no longer true. See https://wagtail.io/blog/wagtail-1-5/, which discusses Wagtail 1.5's support for third party editors _and_ table blocks.

**Comment by SalahAdDin** [comment]
> > We don't support any alternative WYSIWYG editors, because this would require heavily customising each editor to work within Wagtail
> 
> This comment - from nearly two years ago - is no longer true. See https://wagtail.io/blog/wagtail-1-5/, which discusses Wagtail 1.5's support for third-party editors _and_ table blocks.

How is it working today?
