### ISSUE TITLE
Invalid subpage paths result in DoesNotExist exception

### ISSUE THREAD

**Issue by edrex** [torchbox/wagtail#919]
Given page with path `/foo`, attempting to access the invalid subpage path `/foo/bar` results in a 500.

Trace: http://dpaste.com/3AB315K

Seems that the view just needs to catch the exception

**Comment by gasman** [comment]
It looks like this is being triggered by some custom behaviour in your own app. Normally, the `Page.DoesNotExist` exception would be caught within `Page.route`: https://github.com/torchbox/wagtail/blob/master/wagtail/wagtailcore/models.py#L453-456

From your stack trace, it seems that the call to `self.get_children()` is returning a QuerySet of `DataGap` objects rather than `Page` objects as expected - and apparently `DataGap` is not a subclass of `Page` (because the `DataGap.DoesNotExist` exception is not being caught by the `except Page.DoesNotExist:` line).

**Comment by edrex** [comment]
It totally is, it was making some bells ring but I didn't look into it because it was the end of day. Sorry for the noise!

**Comment by edrex** [comment]
After thinking about this it seems like overriding `get_children` in this was is a bad idea. Instead following the `Events` example from the docs and adding a `MyParentPage.get_x` method.
