### ISSUE TITLE
Would you please bring 'pre' and 'blockquote' into the Hallo.js richtext editor?

### ISSUE THREAD

**Issue by kidlj** [torchbox/wagtail#921]
Since we have too many heading tags(H2, H3, H4, H5). I think.

**Comment by gasman** [comment]
Hi @kidlj,
You can customise the hallo.js editor to include extra buttons as described here: https://jossingram.wordpress.com/2014/07/24/add-some-blockquote-buttons-to-wagtail-cms-wysiwyg-editor/

We don't include elements like `pre` and `blockquote` by default, because we want to discourage using rich text areas for complex, structured content - they're only intended for simple text formatting. The next release of Wagtail will include a new field type, StreamField (#823) which will provide a better way to implement 'mixed' content like this.

**Comment by SalahAdDin** [comment]
Perhaps you can put a mini demo in wagtaildemo for can see this customs buttons implemented.
Thank you.
