### ISSUE TITLE
Hyphens in search query are normalized differently than in ElasticSearch

### ISSUE THREAD

**Issue by edrex** [torchbox/wagtail#937]
If I have the substring "fooo-baar" in the text of one of the indexed fields for a Page-derived model instance, I'd expect to be see that page when I search for "fooo-baar", but I don't.

This seems to be because `wagtailsearch` normalizes "fooo-baar" to "fooobaar", while ElasticSearch treats the hyphen as a whitespace character.

Failing test: add 

```
"Hello-world",
```

to `test_queries:45`.

Suggested fix: normalize to "fooo baar" instead.

**Comment by edrex** [comment]
Generally, it seems like `normalise_query_string` should probably be treating punctuation characters as whitespace rather than stripping them.

**Comment by kaedroho** [comment]
Yep, I agree. Thanks for spotting!

The punctuation stripping was actually implemented to work around another bug* in the Elasticsearch backend which is now fixed. It may be safe now to just send the unnormalised query string to Elasticsearch and let it decide what do do with the punctuation.

* We we're previously performing a ``query`` query instead of a ``match`` query in Elasticsearch which took punctuation to mean commands. This caused a few headaches/crashes.
