### ISSUE TITLE
Move django-libsass dependency from the wagtail package to the project template

### ISSUE THREAD

**Issue by kaedroho** [torchbox/wagtail#958]
I think this should be moved into the templates requirements.txt. AFAIK, it isn't called directly within Wagtail (it is pulled in through the ``COMPRESS_PRECOMPILERS`` setting in the project itself).

Removing it will also greatly improve speed of installing wagtail to the host machine for running the ``wagtail start`` command.

**Comment by SalahAdDin** [comment]
I don't undertstando you very good, but, i have a big problem because i couldn't install libsass in my web server, i have ask help to web servers supporters, and then of a large and hardly process, i could install libsass, then i could install django-libsass and finally, i can see all styles of wagtail admin.

**Comment by tomdyson** [comment]
@gasman and @kaedroho can we discuss? @kaedroho, did you mean "it is *not* called directly within Wagtail"?

**Comment by dbsima** [comment]
I already have a fork for which I removed the libsass dependency. https://github.com/dbsima/wagtail/tree/stable/0.8.x

**Comment by gasman** [comment]
@dbsima Just to clarify, we're not considering dropping libsass completely, as developing wagtailadmin's styles in SCSS is still useful to us. This is just about moving the dependency from the wagtail package to the project template, so that people using virtual machines (e.g. Vagrant) don't have to install it on the host machine.

**Comment by zerolab** [comment]
Done in #985/#1019
